import { createHash } from "node:crypto";
import { spawn } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

import { AutoCliError, isAutoCliError } from "../errors.js";
import { maybeAutoRefreshSession } from "../utils/autorefresh.js";
import { getPlatformHomeUrl, getPlatformOrigin } from "../platforms/config.js";
import { parseYouTubeChannelTarget, parseYouTubePlaylistTarget, parseYouTubeTarget } from "../utils/targets.js";
import { BasePlatformAdapter } from "./base.js";
import { Cookie, CookieJar } from "tough-cookie";

import type {
  AdapterActionResult,
  AdapterStatusResult,
  CommentInput,
  LikeInput,
  LoginInput,
  PlatformSession,
  PostMediaInput,
  SessionStatus,
  TextPostInput,
} from "../types.js";

const YOUTUBE_ORIGIN = getPlatformOrigin("youtube");
const YOUTUBE_HOME = getPlatformHomeUrl("youtube");
const YOUTUBE_WATCH = `${YOUTUBE_ORIGIN}/watch?v=`;
const YOUTUBE_CLIENT_NAME = "WEB";
const YOUTUBE_CLIENT_NAME_ID = "1";
const YOUTUBE_USER_AGENT =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36";
const YOUTUBE_COOKIE_ALLOWLIST = new Set([
  "APISID",
  "CONSENT",
  "GPS",
  "HSID",
  "LOGIN_INFO",
  "PREF",
  "SAPISID",
  "SID",
  "SIDCC",
  "SSID",
  "VISITOR_INFO1_LIVE",
  "YSC",
  "__Secure-1PAPISID",
  "__Secure-1PSID",
  "__Secure-1PSIDCC",
  "__Secure-1PSIDTS",
  "__Secure-3PAPISID",
  "__Secure-3PSID",
  "__Secure-3PSIDCC",
  "__Secure-3PSIDTS",
]);

interface YouTubeProbe {
  status: SessionStatus;
  metadata?: Record<string, unknown>;
}

interface YouTubePageConfig {
  apiKey?: string;
  clientVersion?: string;
  visitorData?: string;
  delegatedSessionId?: string;
  sessionIndex?: string;
  createCommentParams?: string;
  loggedIn?: boolean;
}

interface YouTubeActionContext {
  client: Awaited<ReturnType<YouTubeAdapter["createYouTubeClient"]>>;
  page: YouTubePageConfig;
  apiKey: string;
  clientVersion: string;
  url: string;
}

interface YouTubeSearchResultItem {
  id: string;
  title: string;
  url: string;
  channel?: string;
  duration?: string;
  views?: string;
  published?: string;
  description?: string;
  thumbnailUrl?: string;
}

interface YouTubeVideoInfo {
  id: string;
  title: string;
  url: string;
  channel?: string;
  channelId?: string;
  channelUrl?: string;
  duration?: string;
  durationSeconds?: number;
  views?: string;
  published?: string;
  description?: string;
  category?: string;
  thumbnailUrl?: string;
  live?: boolean;
}

interface YouTubeChannelInfo {
  id: string;
  title: string;
  url: string;
  handle?: string;
  description?: string;
  subscriberCount?: string;
  avatarUrl?: string;
  rssUrl?: string;
}

interface YouTubePlaylistItem {
  id: string;
  title: string;
  url: string;
  channel?: string;
  duration?: string;
  thumbnailUrl?: string;
}

interface YouTubePlaylistInfo {
  id: string;
  title: string;
  url: string;
  videoCount?: string;
  viewCount?: string;
  updated?: string;
  thumbnailUrl?: string;
  items: YouTubePlaylistItem[];
}

interface YouTubeCaptionTrack {
  language: string;
  languageCode: string;
  kind?: string;
  autoGenerated: boolean;
  isTranslatable?: boolean;
}

export class YouTubeAdapter extends BasePlatformAdapter {
  readonly platform = "youtube" as const;

  async login(input: LoginInput): Promise<AdapterActionResult> {
    const imported = await this.cookieManager.importCookies(this.platform, input);
    const probe = await this.inspectCookieJar(imported.jar);
    const account = input.account ?? "default";
    const sessionPath = await this.saveSession({
      account,
      source: imported.source,
      status: probe.status,
      metadata: probe.metadata,
      jar: imported.jar,
    });

    if (probe.status.state === "expired") {
      throw new AutoCliError("SESSION_EXPIRED", probe.status.message ?? "YouTube session has expired.", {
        details: {
          platform: this.platform,
          account,
          sessionPath,
        },
      });
    }

    return {
      ok: true,
      platform: this.platform,
      account,
      action: "login",
      message:
        probe.status.state === "active"
          ? `Saved YouTube session for ${account}.`
          : `Saved YouTube session for ${account}, but it should be revalidated before heavy use.`,
      sessionPath,
      data: {
        status: probe.status.state,
      },
    };
  }

  async getStatus(account?: string): Promise<AdapterStatusResult> {
    const { session, path } = await this.prepareSession(account);
    const probe = await this.probeSession(session);
    await this.persistSessionState(session, probe);
    return this.buildStatusResult({
      account: session.account,
      sessionPath: path,
      status: probe.status,
      user: session.user,
    });
  }

  async postMedia(_input: PostMediaInput): Promise<AdapterActionResult> {
    throw new AutoCliError(
      "UNSUPPORTED_ACTION",
      "YouTube uploads are not implemented yet. They require a separate Studio upload flow, not just watch-page session actions.",
    );
  }

  async download(input: {
    account?: string;
    target: string;
    outputDir?: string;
    filenameTemplate?: string;
    audioOnly?: boolean;
    audioFormat?: string;
    format?: string;
  }): Promise<AdapterActionResult> {
    const { session } = await this.prepareSession(input.account);
    await this.ensureUsableSession(session);

    const target = parseYouTubeTarget(input.target);
    const context = await this.prepareVideoActionContext(session, target.videoId, target.url);
    const outputDir = resolve(input.outputDir ?? join(process.cwd(), "downloads", "youtube"));
    const filenameTemplate = input.filenameTemplate?.trim() || "%(title)s [%(id)s].%(ext)s";
    const audioOnly = Boolean(input.audioOnly);
    const audioFormat = (input.audioFormat?.trim() || "mp3").toLowerCase();
    const format = input.format?.trim() || (audioOnly ? "bestaudio/best" : "bestvideo*+bestaudio/best");

    await this.requireCommand("yt-dlp", ["--version"], "YTDLP_NOT_FOUND", "yt-dlp is required for youtube download.");
    await this.requireCommand("ffmpeg", ["-version"], "FFMPEG_NOT_FOUND", "ffmpeg is required for youtube download.");
    await mkdir(outputDir, { recursive: true });

    const tempDir = await mkdtemp(join(tmpdir(), "autocli-youtube-download-"));
    const cookiesPath = join(tempDir, "cookies.txt");

    try {
      await writeFile(cookiesPath, this.buildNetscapeCookies(session), "utf8");

      const args = [
        "--cookies",
        cookiesPath,
        "--no-simulate",
        "--no-progress",
        "--no-warnings",
        "--print",
        "after_move:filepath",
        "--output",
        join(outputDir, filenameTemplate),
        "--format",
        format,
      ];

      if (audioOnly) {
        args.push("--extract-audio", "--audio-format", audioFormat);
      }

      args.push(context.url);

      const { stdout, stderr } = await this.runProcess("yt-dlp", args);
      const outputPath = this.extractDownloadedPath(stdout);

      return {
        ok: true,
        platform: this.platform,
        account: session.account,
        action: "download",
        message: `YouTube download completed for ${session.account}.`,
        id: target.videoId,
        url: context.url,
        data: {
          outputPath,
          outputDir,
          audioOnly,
          audioFormat: audioOnly ? audioFormat : undefined,
          format,
          stderr: stderr || undefined,
        },
      };
    } catch (error) {
      if (isAutoCliError(error)) {
        throw error;
      }

      throw new AutoCliError("YOUTUBE_DOWNLOAD_FAILED", "Failed to download the YouTube video.", {
        cause: error,
        details: error instanceof Error ? { message: error.message } : undefined,
      });
    } finally {
      await rm(tempDir, { recursive: true, force: true }).catch(() => undefined);
    }
  }

  async postText(_input: TextPostInput): Promise<AdapterActionResult> {
    throw new AutoCliError(
      "UNSUPPORTED_ACTION",
      "YouTube community posting is not implemented yet. The current CLI supports engagement actions on videos and channels.",
    );
  }

  async like(input: LikeInput): Promise<AdapterActionResult> {
    const { session } = await this.prepareSession(input.account);
    await this.ensureUsableSession(session);

    const target = parseYouTubeTarget(input.target);
    const context = await this.prepareVideoActionContext(session, target.videoId, target.url);

    await this.executeVideoPreferenceMutation({
      context,
      videoId: target.videoId,
      path: "like/like",
      expectedLikeStatus: "LIKE",
      fallbackMessage: "Failed to like the YouTube video.",
    });

    return {
      ok: true,
      platform: this.platform,
      account: session.account,
      action: "like",
      message: `YouTube video liked for ${session.account}.`,
      id: target.videoId,
      url: context.url,
    };
  }

  async dislike(input: LikeInput): Promise<AdapterActionResult> {
    const { session } = await this.prepareSession(input.account);
    await this.ensureUsableSession(session);

    const target = parseYouTubeTarget(input.target);
    const context = await this.prepareVideoActionContext(session, target.videoId, target.url);

    await this.executeVideoPreferenceMutation({
      context,
      videoId: target.videoId,
      path: "like/dislike",
      expectedLikeStatus: "DISLIKE",
      fallbackMessage: "Failed to dislike the YouTube video.",
    });

    return {
      ok: true,
      platform: this.platform,
      account: session.account,
      action: "dislike",
      message: `YouTube video disliked for ${session.account}.`,
      id: target.videoId,
      url: context.url,
    };
  }

  async unlike(input: LikeInput): Promise<AdapterActionResult> {
    const { session } = await this.prepareSession(input.account);
    await this.ensureUsableSession(session);

    const target = parseYouTubeTarget(input.target);
    const context = await this.prepareVideoActionContext(session, target.videoId, target.url);

    await this.executeVideoPreferenceMutation({
      context,
      videoId: target.videoId,
      path: "like/removelike",
      expectedLikeStatus: "INDIFFERENT",
      fallbackMessage: "Failed to remove the YouTube like/dislike state.",
    });

    return {
      ok: true,
      platform: this.platform,
      account: session.account,
      action: "unlike",
      message: `YouTube video preference cleared for ${session.account}.`,
      id: target.videoId,
      url: context.url,
    };
  }

  async comment(input: CommentInput): Promise<AdapterActionResult> {
    const { session } = await this.prepareSession(input.account);
    await this.ensureUsableSession(session);

    const target = parseYouTubeTarget(input.target);
    const context = await this.prepareVideoActionContext(session, target.videoId, target.url);
    const watchUrl = context.url;
    const createCommentParams = this.requirePageField(
      context.page.createCommentParams,
      "YouTube createCommentParams token",
      "YouTube did not expose a comment token for this video. Comments may be disabled, or the page needs a fresh logged-in cookie export.",
    );

    try {
      await context.client.request(this.buildYoutubeiUrl("comment/create_comment", context.apiKey), {
        method: "POST",
        expectedStatus: 200,
        headers: await this.buildYouTubeApiHeaders(context.client, {
          clientVersion: context.clientVersion,
          visitorData: context.page.visitorData,
          delegatedSessionId: context.page.delegatedSessionId,
          sessionIndex: context.page.sessionIndex,
          referer: watchUrl,
        }),
        body: JSON.stringify({
          context: this.buildYouTubeContext({
            clientVersion: context.clientVersion,
            visitorData: context.page.visitorData,
            originalUrl: watchUrl,
          }),
          createCommentParams,
          commentText: input.text,
        }),
      });
    } catch (error) {
      throw this.mapYouTubeWriteError(error, "Failed to comment on the YouTube video.");
    }

    return {
      ok: true,
      platform: this.platform,
      account: session.account,
      action: "comment",
      message: `YouTube comment sent for ${session.account}.`,
      id: target.videoId,
      url: watchUrl,
      data: {
        text: input.text,
      },
    };
  }

  async search(input: {
    account?: string;
    query: string;
    limit?: number;
  }): Promise<AdapterActionResult> {
    const { session } = await this.prepareSession(input.account);
    await this.ensureUsableSession(session);

    const query = input.query.trim();
    if (!query) {
      throw new AutoCliError("INVALID_SEARCH_QUERY", "Expected a non-empty YouTube search query.");
    }

    const limit = this.normalizeSearchLimit(input.limit);
    const client = await this.createYouTubeClient(session);
    const resultsUrl = `${YOUTUBE_ORIGIN}/results?search_query=${encodeURIComponent(query)}`;
    const context = await this.preparePageActionContext(client, YOUTUBE_HOME);

    let results: YouTubeSearchResultItem[];
    let estimatedResults: string | undefined;

    try {
      const response = await context.client.request<Record<string, unknown>>(
        this.buildYoutubeiUrl("search", context.apiKey),
        {
          method: "POST",
          expectedStatus: 200,
          headers: await this.buildYouTubeApiHeaders(context.client, {
            clientVersion: context.clientVersion,
            visitorData: context.page.visitorData,
            delegatedSessionId: context.page.delegatedSessionId,
            sessionIndex: context.page.sessionIndex,
            referer: resultsUrl,
          }),
          body: JSON.stringify({
            context: this.buildYouTubeContext({
              clientVersion: context.clientVersion,
              visitorData: context.page.visitorData,
              originalUrl: resultsUrl,
            }),
            query,
          }),
        },
      );

      results = this.extractSearchResults(response, limit);
      estimatedResults =
        "estimatedResults" in response && typeof response.estimatedResults === "string"
          ? response.estimatedResults
          : undefined;
    } catch (error) {
      throw this.mapYouTubeWriteError(error, "Failed to search YouTube.");
    }

    return {
      ok: true,
      platform: this.platform,
      account: session.account,
      action: "search",
      message:
        results.length > 0
          ? `Found ${results.length} YouTube video result${results.length === 1 ? "" : "s"} for "${query}".`
          : `No YouTube video results found for "${query}".`,
      url: resultsUrl,
      data: {
        query,
        limit,
        estimatedResults,
        results,
      },
    };
  }

  async info(input: {
    account?: string;
    target: string;
  }): Promise<AdapterActionResult> {
    const { session } = await this.prepareSession(input.account);
    await this.ensureUsableSession(session);

    const target = parseYouTubeTarget(input.target);
    const context = await this.prepareVideoActionContext(session, target.videoId, target.url);

    let info: YouTubeVideoInfo;
    try {
      const response = await context.client.request<Record<string, unknown>>(
        this.buildYoutubeiUrl("player", context.apiKey),
        {
          method: "POST",
          expectedStatus: 200,
          headers: await this.buildYouTubeApiHeaders(context.client, {
            clientVersion: context.clientVersion,
            visitorData: context.page.visitorData,
            delegatedSessionId: context.page.delegatedSessionId,
            sessionIndex: context.page.sessionIndex,
            referer: context.url,
          }),
          body: JSON.stringify({
            context: this.buildYouTubeContext({
              clientVersion: context.clientVersion,
              visitorData: context.page.visitorData,
              originalUrl: context.url,
            }),
            videoId: target.videoId,
          }),
        },
      );

      info = this.parseVideoInfoResponse(response, target.videoId, context.url);
    } catch (error) {
      throw this.mapYouTubeWriteError(error, "Failed to fetch YouTube video details.");
    }

    return {
      ok: true,
      platform: this.platform,
      account: session.account,
      action: "videoid",
      message: `Loaded YouTube video details for ${info.id}.`,
      id: info.id,
      url: info.url,
      data: { ...info },
    };
  }

  async channelInfo(input: {
    account?: string;
    target: string;
  }): Promise<AdapterActionResult> {
    const { session } = await this.prepareSession(input.account);
    await this.ensureUsableSession(session);

    const client = await this.createYouTubeClient(session);
    const target = await this.resolveChannelTarget(client, input.target);
    const html = await this.loadPageHtml(client, target.url);
    const info = this.parseChannelInfoFromHtml(html, target.channelId, target.url);

    return {
      ok: true,
      platform: this.platform,
      account: session.account,
      action: "channelid",
      message: `Loaded YouTube channel details for ${info.id}.`,
      id: info.id,
      url: info.url,
      data: { ...info },
    };
  }

  async playlistInfo(input: {
    account?: string;
    target: string;
    limit?: number;
  }): Promise<AdapterActionResult> {
    const { session } = await this.prepareSession(input.account);
    await this.ensureUsableSession(session);

    const client = await this.createYouTubeClient(session);
    const target = parseYouTubePlaylistTarget(input.target);
    const url = target.url ?? `${YOUTUBE_ORIGIN}/playlist?list=${encodeURIComponent(target.playlistId)}`;
    const html = await this.loadPageHtml(client, url);
    const limit = this.normalizeSearchLimit(input.limit);
    const info = this.parsePlaylistInfoFromHtml(html, target.playlistId, url, limit);

    return {
      ok: true,
      platform: this.platform,
      account: session.account,
      action: "playlistid",
      message: `Loaded YouTube playlist details for ${info.id}.`,
      id: info.id,
      url: info.url,
      data: { ...info, items: info.items.map((item) => ({ ...item })) },
    };
  }

  async related(input: {
    account?: string;
    target: string;
    limit?: number;
  }): Promise<AdapterActionResult> {
    const { session } = await this.prepareSession(input.account);
    await this.ensureUsableSession(session);

    const target = parseYouTubeTarget(input.target);
    const context = await this.prepareVideoActionContext(session, target.videoId, target.url);
    const limit = this.normalizeSearchLimit(input.limit);

    let results: YouTubeSearchResultItem[];
    try {
      const response = await context.client.request<Record<string, unknown>>(
        this.buildYoutubeiUrl("next", context.apiKey),
        {
          method: "POST",
          expectedStatus: 200,
          headers: await this.buildYouTubeApiHeaders(context.client, {
            clientVersion: context.clientVersion,
            visitorData: context.page.visitorData,
            delegatedSessionId: context.page.delegatedSessionId,
            sessionIndex: context.page.sessionIndex,
            referer: context.url,
          }),
          body: JSON.stringify({
            context: this.buildYouTubeContext({
              clientVersion: context.clientVersion,
              visitorData: context.page.visitorData,
              originalUrl: context.url,
            }),
            videoId: target.videoId,
          }),
        },
      );

      results = this.extractRelatedResults(response, target.videoId, limit);
    } catch (error) {
      throw this.mapYouTubeWriteError(error, "Failed to load related YouTube videos.");
    }

    return {
      ok: true,
      platform: this.platform,
      account: session.account,
      action: "related",
      message:
        results.length > 0
          ? `Found ${results.length} related YouTube video result${results.length === 1 ? "" : "s"}.`
          : "No related YouTube videos found.",
      id: target.videoId,
      url: context.url,
      data: {
        targetVideoId: target.videoId,
        limit,
        results: results.map((item) => ({ ...item })),
      },
    };
  }

  async captions(input: {
    account?: string;
    target: string;
  }): Promise<AdapterActionResult> {
    const { session } = await this.prepareSession(input.account);
    await this.ensureUsableSession(session);

    const target = parseYouTubeTarget(input.target);
    const context = await this.prepareVideoActionContext(session, target.videoId, target.url);

    let tracks: YouTubeCaptionTrack[];
    try {
      const response = await context.client.request<Record<string, unknown>>(
        this.buildYoutubeiUrl("player", context.apiKey),
        {
          method: "POST",
          expectedStatus: 200,
          headers: await this.buildYouTubeApiHeaders(context.client, {
            clientVersion: context.clientVersion,
            visitorData: context.page.visitorData,
            delegatedSessionId: context.page.delegatedSessionId,
            sessionIndex: context.page.sessionIndex,
            referer: context.url,
          }),
          body: JSON.stringify({
            context: this.buildYouTubeContext({
              clientVersion: context.clientVersion,
              visitorData: context.page.visitorData,
              originalUrl: context.url,
            }),
            videoId: target.videoId,
          }),
        },
      );

      tracks = this.extractCaptionTracks(response);
    } catch (error) {
      throw this.mapYouTubeWriteError(error, "Failed to load YouTube caption tracks.");
    }

    return {
      ok: true,
      platform: this.platform,
      account: session.account,
      action: "captions",
      message:
        tracks.length > 0
          ? `Found ${tracks.length} YouTube caption track${tracks.length === 1 ? "" : "s"}.`
          : "No YouTube caption tracks found.",
      id: target.videoId,
      url: context.url,
      data: {
        targetVideoId: target.videoId,
        tracks: tracks.map((track) => ({ ...track })),
      },
    };
  }

  async subscribe(input: LikeInput): Promise<AdapterActionResult> {
    const { session } = await this.prepareSession(input.account);
    await this.ensureUsableSession(session);

    const client = await this.createYouTubeClient(session);
    const target = await this.resolveChannelTarget(client, input.target);
    const context = await this.preparePageActionContext(client, target.url);

    await this.executeSubscriptionMutation({
      context,
      channelId: target.channelId,
      path: "subscription/subscribe",
      expectedSubscribed: true,
      fallbackMessage: "Failed to subscribe to the YouTube channel.",
    });

    return {
      ok: true,
      platform: this.platform,
      account: session.account,
      action: "subscribe",
      message: `YouTube channel subscribed for ${session.account}.`,
      id: target.channelId,
      url: target.url,
    };
  }

  async unsubscribe(input: LikeInput): Promise<AdapterActionResult> {
    const { session } = await this.prepareSession(input.account);
    await this.ensureUsableSession(session);

    const client = await this.createYouTubeClient(session);
    const target = await this.resolveChannelTarget(client, input.target);
    const context = await this.preparePageActionContext(client, target.url);

    await this.executeSubscriptionMutation({
      context,
      channelId: target.channelId,
      path: "subscription/unsubscribe",
      expectedSubscribed: false,
      fallbackMessage: "Failed to unsubscribe from the YouTube channel.",
    });

    return {
      ok: true,
      platform: this.platform,
      account: session.account,
      action: "unsubscribe",
      message: `YouTube channel unsubscribed for ${session.account}.`,
      id: target.channelId,
      url: target.url,
    };
  }

  private async ensureUsableSession(session: PlatformSession): Promise<void> {
    const probe = await this.probeSession(session);
    await this.persistSessionState(session, probe);

    if (probe.status.state === "expired") {
      throw new AutoCliError("SESSION_EXPIRED", probe.status.message ?? "YouTube session has expired.", {
        details: {
          platform: this.platform,
          account: session.account,
        },
      });
    }
  }

  private async prepareSession(account?: string): Promise<{ session: PlatformSession; path: string }> {
    const loaded = await this.loadSession(account);
    return {
      path: loaded.path,
      session: await this.maybeAutoRefresh(loaded.session),
    };
  }

  private async maybeAutoRefresh(session: PlatformSession): Promise<PlatformSession> {
    const client = await this.createYouTubeClient(session);
    const refresh = await maybeAutoRefreshSession({
      platform: this.platform,
      session,
      jar: client.jar,
      strategy: "homepage_keepalive",
      capability: "auto",
      refresh: async () => {
        await client.request<string>(YOUTUBE_HOME, {
          responseType: "text",
          expectedStatus: 200,
        });
      },
    });

    return this.persistExistingSession(session, {
      jar: client.jar,
      metadata: {
        ...(session.metadata ?? {}),
        ...refresh.metadata,
      },
    });
  }

  private async probeSession(session: PlatformSession): Promise<YouTubeProbe> {
    const jar = await this.cookieManager.createJar(session);
    return this.inspectCookieJar(jar);
  }

  private async inspectCookieJar(jar: CookieJar): Promise<YouTubeProbe> {
    const client = await this.createYouTubeClientFromJar(jar);
    const authCookie = await this.getAuthCookieValue(client);
    const loginCookie =
      (await client.getCookieValue("LOGIN_INFO", YOUTUBE_HOME)) ??
      (await client.getCookieValue("SID", YOUTUBE_HOME)) ??
      (await client.getCookieValue("__Secure-3PSID", YOUTUBE_HOME));

    if (!authCookie || !loginCookie) {
      return {
        status: {
          state: "expired",
          message: "Missing required YouTube auth cookies. Re-import cookies.txt from a logged-in browser session.",
          lastValidatedAt: new Date().toISOString(),
          lastErrorCode: "COOKIE_MISSING",
        },
      };
    }

    try {
      const html = await client.request<string>(YOUTUBE_HOME, {
        responseType: "text",
        expectedStatus: 200,
      });
      const page = this.parseYouTubePageConfig(html);

      if (page.loggedIn === true) {
        return {
          status: {
            state: "active",
            message: "Session validated via the YouTube homepage.",
            lastValidatedAt: new Date().toISOString(),
          },
          metadata: this.toMetadata(page),
        };
      }

      if (page.loggedIn === false) {
        return {
          status: {
            state: "expired",
            message: "YouTube returned a logged-out homepage. Re-import cookies.txt.",
            lastValidatedAt: new Date().toISOString(),
            lastErrorCode: "AUTH_FAILED",
          },
          metadata: this.toMetadata(page),
        };
      }

      return {
        status: {
          state: "unknown",
          message: "YouTube auth cookies are present, but homepage validation was inconclusive.",
          lastValidatedAt: new Date().toISOString(),
        },
        metadata: this.toMetadata(page),
      };
    } catch (error) {
      return {
        status: {
          state: "unknown",
          message: "YouTube auth cookies are present, but homepage validation was unavailable.",
          lastValidatedAt: new Date().toISOString(),
        },
        metadata: isAutoCliError(error) ? error.details : undefined,
      };
    }
  }

  private async createYouTubeClient(session: PlatformSession) {
    const jar = await this.cookieManager.createJar(session);
    return this.createYouTubeClientFromJar(jar);
  }

  private async createYouTubeClientFromJar(jar: CookieJar) {
    const filteredJar = await this.filterYouTubeCookies(jar);
    return new (await import("../utils/http-client.js")).SessionHttpClient(filteredJar, {
      accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
      "accept-language": "en-US,en;q=0.9",
      "user-agent": YOUTUBE_USER_AGENT,
    });
  }

  private normalizeSearchLimit(limit?: number): number {
    if (!limit || !Number.isFinite(limit)) {
      return 5;
    }

    return Math.max(1, Math.min(25, Math.floor(limit)));
  }

  private buildNetscapeCookies(session: PlatformSession): string {
    const header = ["# Netscape HTTP Cookie File", "# This file was generated by AutoCLI.", ""];
    const cookies = Array.isArray(session.cookieJar.cookies) ? session.cookieJar.cookies : [];

    const lines = cookies
      .filter(
        (cookie): cookie is {
          key: string;
          value: string;
          domain?: string;
          path?: string;
          secure?: boolean;
          expires?: string | number | Date;
          hostOnly?: boolean;
        } => Boolean(cookie && typeof cookie.key === "string" && typeof cookie.value === "string"),
      )
      .map((cookie) => {
        const domain = cookie.domain ?? "youtube.com";
        const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
        const path = cookie.path ?? "/";
        const secure = cookie.secure ? "TRUE" : "FALSE";
        const expires = this.toNetscapeExpiry(cookie.expires);
        return [domain, includeSubdomains, path, secure, String(expires), cookie.key, cookie.value].join("\t");
      });

    return [...header, ...lines, ""].join("\n");
  }

  private toNetscapeExpiry(value: unknown): number {
    if (typeof value === "number" && Number.isFinite(value)) {
      return value > 10_000_000_000 ? Math.floor(value / 1_000) : Math.floor(value);
    }

    if (typeof value === "string") {
      if (!value || value === "Infinity") {
        return 0;
      }

      const asNumber = Number(value);
      if (!Number.isNaN(asNumber)) {
        return asNumber > 10_000_000_000 ? Math.floor(asNumber / 1_000) : Math.floor(asNumber);
      }

      const parsed = Date.parse(value);
      return Number.isNaN(parsed) ? 0 : Math.floor(parsed / 1_000);
    }

    if (value instanceof Date) {
      return Math.floor(value.getTime() / 1_000);
    }

    return 0;
  }

  private async requireCommand(
    command: string,
    args: string[],
    errorCode: string,
    errorMessage: string,
  ): Promise<void> {
    try {
      await this.runProcess(command, args);
    } catch (error) {
      if (
        error instanceof Error &&
        "cause" in error &&
        error.cause &&
        typeof error.cause === "object" &&
        "code" in error.cause &&
        error.cause.code === "ENOENT"
      ) {
        throw new AutoCliError(errorCode, errorMessage, {
          details: {
            command,
          },
          cause: error,
        });
      }

      throw error;
    }
  }

  private async runProcess(
    command: string,
    args: string[],
  ): Promise<{ stdout: string; stderr: string }> {
    return new Promise((resolvePromise, rejectPromise) => {
      const child = spawn(command, args, {
        stdio: ["ignore", "pipe", "pipe"],
      });

      let stdout = "";
      let stderr = "";

      child.stdout.on("data", (chunk) => {
        stdout += String(chunk);
      });

      child.stderr.on("data", (chunk) => {
        stderr += String(chunk);
      });

      child.on("error", (error) => {
        rejectPromise(new Error(`Failed to start ${command}.`, { cause: error }));
      });

      child.on("close", (code) => {
        if (code === 0) {
          resolvePromise({ stdout, stderr });
          return;
        }

        rejectPromise(
          new AutoCliError("PROCESS_FAILED", `${command} exited with code ${code ?? "unknown"}.`, {
            details: {
              command,
              args,
              code: code ?? undefined,
              stderr: stderr.trim() || undefined,
            },
          }),
        );
      });
    });
  }

  private extractDownloadedPath(stdout: string): string | undefined {
    const lines = stdout
      .split(/\r?\n/u)
      .map((line) => line.trim())
      .filter(Boolean);

    return lines.at(-1);
  }

  private async prepareVideoActionContext(
    session: PlatformSession,
    videoId: string,
    inputUrl?: string,
  ): Promise<YouTubeActionContext> {
    const client = await this.createYouTubeClient(session);
    const url = inputUrl ?? `${YOUTUBE_WATCH}${videoId}`;
    return this.preparePageActionContext(client, url);
  }

  private async preparePageActionContext(
    client: Awaited<ReturnType<YouTubeAdapter["createYouTubeClient"]>>,
    url: string,
  ): Promise<YouTubeActionContext> {
    const page = await this.loadPageContext(client, url);
    return {
      client,
      page,
      apiKey: this.requirePageField(page.apiKey, "YouTube API key"),
      clientVersion: this.requirePageField(page.clientVersion, "YouTube client version"),
      url,
    };
  }

  private async executeVideoPreferenceMutation(input: {
    context: YouTubeActionContext;
    videoId: string;
    path: string;
    expectedLikeStatus: "LIKE" | "DISLIKE" | "INDIFFERENT";
    fallbackMessage: string;
  }): Promise<void> {
    try {
      const response = await input.context.client.request<Record<string, unknown>>(
        this.buildYoutubeiUrl(input.path, input.context.apiKey),
        {
          method: "POST",
          expectedStatus: 200,
          headers: await this.buildYouTubeApiHeaders(input.context.client, {
            clientVersion: input.context.clientVersion,
            visitorData: input.context.page.visitorData,
            delegatedSessionId: input.context.page.delegatedSessionId,
            sessionIndex: input.context.page.sessionIndex,
            referer: input.context.url,
          }),
          body: JSON.stringify({
            context: this.buildYouTubeContext({
              clientVersion: input.context.clientVersion,
              visitorData: input.context.page.visitorData,
              originalUrl: input.context.url,
            }),
            target: {
              videoId: input.videoId,
            },
          }),
        },
      );

      const likeStatus = this.extractLikeStatus(response);
      if (likeStatus && likeStatus !== input.expectedLikeStatus) {
        throw new AutoCliError("YOUTUBE_REQUEST_REJECTED", "YouTube did not apply the requested video preference.", {
          details: {
            expectedLikeStatus: input.expectedLikeStatus,
            actualLikeStatus: likeStatus,
            path: input.path,
          },
        });
      }
    } catch (error) {
      throw this.mapYouTubeWriteError(error, input.fallbackMessage);
    }
  }

  private async executeSubscriptionMutation(input: {
    context: YouTubeActionContext;
    channelId: string;
    path: string;
    expectedSubscribed: boolean;
    fallbackMessage: string;
  }): Promise<void> {
    try {
      const response = await input.context.client.request<Record<string, unknown>>(
        this.buildYoutubeiUrl(input.path, input.context.apiKey),
        {
          method: "POST",
          expectedStatus: [200, 404],
          headers: await this.buildYouTubeApiHeaders(input.context.client, {
            clientVersion: input.context.clientVersion,
            visitorData: input.context.page.visitorData,
            delegatedSessionId: input.context.page.delegatedSessionId,
            sessionIndex: input.context.page.sessionIndex,
            referer: input.context.url,
          }),
          body: JSON.stringify({
            context: this.buildYouTubeContext({
              clientVersion: input.context.clientVersion,
              visitorData: input.context.page.visitorData,
              originalUrl: input.context.url,
            }),
            channelIds: [input.channelId],
          }),
        },
      );

      const modalMessage = this.extractSubscriptionErrorMessage(response);
      if (modalMessage) {
        throw new AutoCliError("YOUTUBE_REQUEST_REJECTED", modalMessage, {
          details: {
            channelId: input.channelId,
            path: input.path,
          },
        });
      }

      const subscribedState = this.extractSubscribedState(response, input.channelId);
      if (typeof subscribedState === "boolean" && subscribedState !== input.expectedSubscribed) {
        throw new AutoCliError("YOUTUBE_REQUEST_REJECTED", "YouTube did not apply the requested subscription state.", {
          details: {
            channelId: input.channelId,
            expectedSubscribed: input.expectedSubscribed,
            actualSubscribed: subscribedState,
            path: input.path,
          },
        });
      }
    } catch (error) {
      throw this.mapYouTubeWriteError(error, input.fallbackMessage);
    }
  }

  private async loadWatchPageContext(
    client: Awaited<ReturnType<YouTubeAdapter["createYouTubeClient"]>>,
    videoId: string,
  ): Promise<YouTubePageConfig> {
    return this.loadPageContext(client, `${YOUTUBE_WATCH}${videoId}`);
  }

  private async loadPageHtml(
    client: Awaited<ReturnType<YouTubeAdapter["createYouTubeClient"]>>,
    url: string,
  ): Promise<string> {
    return client.request<string>(url, {
      responseType: "text",
      expectedStatus: 200,
      headers: {
        referer: YOUTUBE_HOME,
      },
    });
  }

  private async loadPageContext(
    client: Awaited<ReturnType<YouTubeAdapter["createYouTubeClient"]>>,
    url: string,
  ): Promise<YouTubePageConfig> {
    const html = await this.loadPageHtml(client, url);
    const page = this.parseYouTubePageConfig(html);
    if (page.loggedIn === false) {
      throw new AutoCliError("SESSION_EXPIRED", "YouTube returned a logged-out page. Re-import cookies.txt.");
    }

    return page;
  }

  private parseYouTubePageConfig(html: string): YouTubePageConfig {
    return {
      apiKey: this.matchQuotedValue(html, /"INNERTUBE_API_KEY":"([^"]+)"/),
      clientVersion: this.matchQuotedValue(html, /"INNERTUBE_CLIENT_VERSION":"([^"]+)"/),
      visitorData: this.matchQuotedValue(html, /"VISITOR_DATA":"([^"]+)"/),
      delegatedSessionId: this.matchQuotedValue(html, /"DELEGATED_SESSION_ID":"([^"]+)"/),
      sessionIndex: this.matchQuotedValue(html, /"SESSION_INDEX":"?([^",}]+)"?/),
      createCommentParams: this.matchQuotedValue(html, /"createCommentParams":"([^"]+)"/),
      loggedIn: this.matchBoolean(html, /"LOGGED_IN":(true|false)/),
    };
  }

  private matchQuotedValue(html: string, pattern: RegExp): string | undefined {
    const match = html.match(pattern);
    if (!match?.[1]) {
      return undefined;
    }

    try {
      return JSON.parse(`"${match[1]}"`) as string;
    } catch {
      return match[1];
    }
  }

  private matchBoolean(html: string, pattern: RegExp): boolean | undefined {
    const match = html.match(pattern);
    if (!match?.[1]) {
      return undefined;
    }

    return match[1] === "true";
  }

  private toMetadata(page: YouTubePageConfig): Record<string, unknown> {
    return {
      ...(page.apiKey ? { apiKey: page.apiKey } : {}),
      ...(page.clientVersion ? { clientVersion: page.clientVersion } : {}),
      ...(page.visitorData ? { visitorData: page.visitorData } : {}),
      ...(page.delegatedSessionId ? { delegatedSessionId: page.delegatedSessionId } : {}),
      ...(page.sessionIndex ? { sessionIndex: page.sessionIndex } : {}),
    };
  }

  private requirePageField<T extends string>(
    value: T | undefined,
    fieldLabel: string,
    message?: string,
  ): T {
    if (!value) {
      throw new AutoCliError("YOUTUBE_PAGE_CONFIG_MISSING", message ?? `Missing ${fieldLabel} from the YouTube page.`);
    }

    return value;
  }

  private buildYoutubeiUrl(path: string, apiKey: string): string {
    return `${YOUTUBE_ORIGIN}/youtubei/v1/${path}?prettyPrint=false&key=${encodeURIComponent(apiKey)}`;
  }

  private async buildYouTubeApiHeaders(
    client: Awaited<ReturnType<YouTubeAdapter["createYouTubeClient"]>>,
    input: {
      clientVersion: string;
      visitorData?: string;
      delegatedSessionId?: string;
      sessionIndex?: string;
      referer: string;
    },
  ): Promise<Record<string, string>> {
    const sapisid = await this.getAuthCookieValue(client);
    if (!sapisid) {
      throw new AutoCliError("SESSION_EXPIRED", "YouTube SAPISID cookie is missing. Re-import cookies.txt.");
    }

    return {
      accept: "*/*",
      "accept-language": "en-US,en;q=0.9",
      authorization: buildSapisidHash(sapisid, YOUTUBE_ORIGIN),
      "content-type": "application/json",
      origin: YOUTUBE_ORIGIN,
      referer: input.referer,
      "user-agent": YOUTUBE_USER_AGENT,
      "x-goog-authuser": input.sessionIndex ?? "0",
      ...(input.delegatedSessionId ? { "x-goog-pageid": input.delegatedSessionId } : {}),
      ...(input.visitorData ? { "x-goog-visitor-id": input.visitorData } : {}),
      "x-origin": YOUTUBE_ORIGIN,
      "x-youtube-bootstrap-logged-in": "true",
      "x-youtube-client-name": YOUTUBE_CLIENT_NAME_ID,
      "x-youtube-client-version": input.clientVersion,
    };
  }

  private buildYouTubeContext(input: {
    clientVersion: string;
    visitorData?: string;
    originalUrl: string;
  }): Record<string, unknown> {
    return {
      client: {
        clientName: YOUTUBE_CLIENT_NAME,
        clientVersion: input.clientVersion,
        hl: "en",
        gl: "US",
        visitorData: input.visitorData,
        userAgent: YOUTUBE_USER_AGENT,
        browserName: "Chrome",
        browserVersion: "136.0.0.0",
        osName: "Macintosh",
        osVersion: "10_15_7",
        platform: "DESKTOP",
        clientFormFactor: "UNKNOWN_FORM_FACTOR",
        originalUrl: input.originalUrl,
      },
      user: {
        lockedSafetyMode: false,
      },
      request: {
        useSsl: true,
      },
    };
  }

  private async getAuthCookieValue(
    client: Awaited<ReturnType<YouTubeAdapter["createYouTubeClient"]>>,
  ): Promise<string | undefined> {
    return (
      (await client.getCookieValue("SAPISID", YOUTUBE_HOME)) ??
      (await client.getCookieValue("__Secure-3PAPISID", YOUTUBE_HOME)) ??
      (await client.getCookieValue("APISID", YOUTUBE_HOME)) ??
      (await client.getCookieValue("__Secure-1PAPISID", YOUTUBE_HOME))
    );
  }

  private extractLikeStatus(response: Record<string, unknown>): string | undefined {
    const entityBatchUpdate =
      response.frameworkUpdates &&
      typeof response.frameworkUpdates === "object" &&
      "entityBatchUpdate" in response.frameworkUpdates
        ? response.frameworkUpdates.entityBatchUpdate
        : undefined;

    if (!entityBatchUpdate || typeof entityBatchUpdate !== "object" || !("mutations" in entityBatchUpdate)) {
      return undefined;
    }

    const mutations = Array.isArray(entityBatchUpdate.mutations) ? entityBatchUpdate.mutations : [];
    for (const mutation of mutations) {
      if (!mutation || typeof mutation !== "object") {
        continue;
      }

      const payload = "payload" in mutation ? mutation.payload : undefined;
      if (!payload || typeof payload !== "object" || !("likeStatusEntity" in payload)) {
        continue;
      }

      const likeStatusEntity = payload.likeStatusEntity;
      if (
        likeStatusEntity &&
        typeof likeStatusEntity === "object" &&
        "likeStatus" in likeStatusEntity &&
        typeof likeStatusEntity.likeStatus === "string"
      ) {
        return likeStatusEntity.likeStatus;
      }
    }

    return undefined;
  }

  private extractSubscriptionErrorMessage(response: Record<string, unknown>): string | undefined {
    const actions = Array.isArray(response.actions) ? response.actions : [];
    for (const action of actions) {
      if (!action || typeof action !== "object" || !("openPopupAction" in action)) {
        continue;
      }

      const popup = action.openPopupAction;
      if (!popup || typeof popup !== "object" || !("popup" in popup)) {
        continue;
      }

      const popupRenderer = popup.popup;
      const title = this.extractTextFromRunsPath(popupRenderer, [
        "modalWithTitleAndButtonRenderer",
        "title",
        "runs",
      ]);
      const content = this.extractSimpleTextPath(popupRenderer, [
        "modalWithTitleAndButtonRenderer",
        "content",
        "simpleText",
      ]);

      if (title || content) {
        return [title, content].filter(Boolean).join(": ");
      }
    }

    return undefined;
  }

  private extractSubscribedState(response: Record<string, unknown>, channelId: string): boolean | undefined {
    const actions = Array.isArray(response.actions) ? response.actions : [];
    for (const action of actions) {
      if (!action || typeof action !== "object" || !("updateSubscribeButtonAction" in action)) {
        continue;
      }

      const update = action.updateSubscribeButtonAction;
      if (
        update &&
        typeof update === "object" &&
        "channelId" in update &&
        update.channelId === channelId &&
        "subscribed" in update &&
        typeof update.subscribed === "boolean"
      ) {
        return update.subscribed;
      }
    }

    return undefined;
  }

  private extractTextFromRunsPath(node: unknown, path: string[]): string | undefined {
    const target = this.getNestedValue(node, path);
    if (!Array.isArray(target)) {
      return undefined;
    }

    return target
      .map((entry) =>
        entry && typeof entry === "object" && "text" in entry && typeof entry.text === "string" ? entry.text : "",
      )
      .filter(Boolean)
      .join("");
  }

  private extractSimpleTextPath(node: unknown, path: string[]): string | undefined {
    const target = this.getNestedValue(node, path);
    return typeof target === "string" ? target : undefined;
  }

  private getNestedValue(node: unknown, path: string[]): unknown {
    let current = node;

    for (const key of path) {
      if (!current || typeof current !== "object" || !(key in current)) {
        return undefined;
      }

      current = current[key as keyof typeof current];
    }

    return current;
  }

  private async resolveChannelTarget(
    client: Awaited<ReturnType<YouTubeAdapter["createYouTubeClient"]>>,
    target: string,
  ): Promise<{ channelId: string; url: string }> {
    const parsed = parseYouTubeChannelTarget(target);
    if (parsed.channelId) {
      return {
        channelId: parsed.channelId,
        url: parsed.url ?? `${YOUTUBE_ORIGIN}/channel/${parsed.channelId}`,
      };
    }

    const suffix = parsed.path ?? (parsed.handle ? `/${parsed.handle}` : "");
    const url = parsed.url ?? `${YOUTUBE_ORIGIN}${suffix}`;
    const html = await client.request<string>(url, {
      responseType: "text",
      expectedStatus: 200,
      headers: {
        referer: YOUTUBE_HOME,
      },
    });

    const channelId = this.extractChannelId(html);
    if (!channelId) {
      throw new AutoCliError("YOUTUBE_CHANNEL_RESOLUTION_FAILED", "Could not resolve the YouTube channel ID.", {
        details: {
          target,
          url,
        },
      });
    }

    return {
      channelId,
      url,
    };
  }

  private extractChannelId(html: string): string | undefined {
    return (
      this.matchQuotedValue(html, /"externalId":"(UC[^"]+)"/) ??
      this.matchQuotedValue(html, /"browseId":"(UC[^"]+)"/) ??
      this.matchQuotedValue(html, /"channelId":"(UC[^"]+)"/)
    );
  }

  private parseChannelInfoFromHtml(html: string, channelId: string, url: string): YouTubeChannelInfo {
    const initialData = this.extractAssignedJsonObject(html, "ytInitialData");
    const metadata = this.findRenderer(initialData, "channelMetadataRenderer");
    const title =
      (metadata && "title" in metadata && typeof metadata.title === "string" ? metadata.title : undefined) ??
      this.matchQuotedValue(html, /"channelMetadataRenderer":\{"title":"([^"]+)"/) ??
      "Untitled channel";
    const handle =
      (metadata &&
      "ownerUrls" in metadata &&
      Array.isArray(metadata.ownerUrls) &&
      typeof metadata.ownerUrls[0] === "string"
        ? this.extractHandleFromUrl(metadata.ownerUrls[0])
        : undefined) ??
      this.extractHandleFromUrl(url);

    return {
      id: channelId,
      title,
      url,
      handle,
      description:
        (metadata && "description" in metadata && typeof metadata.description === "string"
          ? metadata.description
          : undefined) ??
        this.matchQuotedValue(html, /"channelMetadataRenderer":\{[^]*?"description":"([^"]*)"/),
      subscriberCount:
        this.matchQuotedValue(html, /"subscriberCountText":\{"simpleText":"([^"]+)"/) ??
        this.matchQuotedValue(html, /"subscriberCountText":\{"accessibility":\{[^]*?"label":"([^"]+)"/),
      avatarUrl:
        (metadata &&
        "avatar" in metadata &&
        metadata.avatar &&
        typeof metadata.avatar === "object"
          ? this.extractThumbnailUrl(metadata.avatar)
          : undefined) ??
        this.matchQuotedValue(html, /"avatar":\{"thumbnails":\[\{"url":"([^"]+)"/),
      rssUrl:
        metadata && "rssUrl" in metadata && typeof metadata.rssUrl === "string" ? metadata.rssUrl : undefined,
    };
  }

  private parsePlaylistInfoFromHtml(html: string, playlistId: string, url: string, limit: number): YouTubePlaylistInfo {
    const initialData = this.extractAssignedJsonObject(html, "ytInitialData");
    const metadata = this.findRenderer(initialData, "playlistMetadataRenderer");
    const sidebar = this.findRenderer(initialData, "playlistSidebarPrimaryInfoRenderer");
    const title =
      (metadata && "title" in metadata && typeof metadata.title === "string" ? metadata.title : undefined) ??
      this.matchQuotedValue(html, /"playlistMetadataRenderer":\{"title":"([^"]+)"/) ??
      "Untitled playlist";
    const stats = sidebar && "stats" in sidebar && Array.isArray(sidebar.stats) ? sidebar.stats : [];
    const items = this.extractPlaylistItems(initialData, limit);

    return {
      id: playlistId,
      title,
      url,
      videoCount: this.extractTextValue(stats[0]),
      viewCount: this.extractTextValue(stats[1]),
      updated: this.extractTextValue(stats[2]),
      thumbnailUrl:
        (sidebar &&
        "thumbnailRenderer" in sidebar &&
        sidebar.thumbnailRenderer &&
        typeof sidebar.thumbnailRenderer === "object"
          ? this.extractNestedThumbnailUrl(sidebar.thumbnailRenderer)
          : undefined) ??
        items[0]?.thumbnailUrl,
      items,
    };
  }

  private parseVideoInfoResponse(
    response: Record<string, unknown>,
    videoId: string,
    url: string,
  ): YouTubeVideoInfo {
    const playabilityStatus =
      "playabilityStatus" in response && response.playabilityStatus && typeof response.playabilityStatus === "object"
        ? response.playabilityStatus
        : undefined;

    const playabilityState =
      playabilityStatus && "status" in playabilityStatus && typeof playabilityStatus.status === "string"
        ? playabilityStatus.status
        : undefined;

    if (playabilityState && playabilityState !== "OK") {
      const reason =
        (playabilityStatus && "reason" in playabilityStatus && typeof playabilityStatus.reason === "string"
          ? playabilityStatus.reason
          : undefined) ?? "Video unavailable";
      throw new AutoCliError("YOUTUBE_VIDEO_UNAVAILABLE", reason, {
        details: {
          videoId,
          playabilityStatus: playabilityState,
        },
      });
    }

    const videoDetails =
      "videoDetails" in response && response.videoDetails && typeof response.videoDetails === "object"
        ? response.videoDetails
        : undefined;
    if (!videoDetails) {
      throw new AutoCliError("YOUTUBE_VIDEO_INFO_MISSING", "YouTube did not return video details.", {
        details: { videoId },
      });
    }

    const microformat =
      "microformat" in response && response.microformat && typeof response.microformat === "object"
        ? response.microformat
        : undefined;
    const playerMicroformat =
      microformat &&
      "playerMicroformatRenderer" in microformat &&
      microformat.playerMicroformatRenderer &&
      typeof microformat.playerMicroformatRenderer === "object"
        ? microformat.playerMicroformatRenderer
        : undefined;

    const durationSeconds =
      "lengthSeconds" in videoDetails && typeof videoDetails.lengthSeconds === "string"
        ? Number.parseInt(videoDetails.lengthSeconds, 10)
        : undefined;
    const parsedViewCount =
      "viewCount" in videoDetails && typeof videoDetails.viewCount === "string"
        ? Number.parseInt(videoDetails.viewCount, 10)
        : undefined;
    const channelId =
      ("channelId" in videoDetails && typeof videoDetails.channelId === "string"
        ? videoDetails.channelId
        : undefined) ??
      (playerMicroformat &&
      "externalChannelId" in playerMicroformat &&
      typeof playerMicroformat.externalChannelId === "string"
        ? playerMicroformat.externalChannelId
        : undefined);

    return {
      id: videoId,
      title:
        ("title" in videoDetails && typeof videoDetails.title === "string" ? videoDetails.title : undefined) ??
        "Untitled video",
      url,
      channel:
        ("author" in videoDetails && typeof videoDetails.author === "string" ? videoDetails.author : undefined) ??
        (playerMicroformat
          ? this.extractTextValue(
              "ownerChannelName" in playerMicroformat ? playerMicroformat.ownerChannelName : undefined,
            )
          : undefined),
      channelId,
      channelUrl: channelId ? `${YOUTUBE_ORIGIN}/channel/${channelId}` : undefined,
      duration:
        typeof durationSeconds === "number" && Number.isFinite(durationSeconds)
          ? formatDuration(durationSeconds)
          : undefined,
      durationSeconds:
        typeof durationSeconds === "number" && Number.isFinite(durationSeconds) ? durationSeconds : undefined,
      views:
        typeof parsedViewCount === "number" && Number.isFinite(parsedViewCount)
          ? `${parsedViewCount.toLocaleString("en-US")} views`
          : undefined,
      published:
        (playerMicroformat &&
        "publishDate" in playerMicroformat &&
        typeof playerMicroformat.publishDate === "string"
          ? playerMicroformat.publishDate
          : undefined) ??
        (playerMicroformat &&
        "uploadDate" in playerMicroformat &&
        typeof playerMicroformat.uploadDate === "string"
          ? playerMicroformat.uploadDate
          : undefined),
      description:
        ("shortDescription" in videoDetails && typeof videoDetails.shortDescription === "string"
          ? videoDetails.shortDescription
          : undefined) ??
        (playerMicroformat ? this.extractDescriptionValue(playerMicroformat as Record<string, unknown>) : undefined),
      category:
        playerMicroformat && "category" in playerMicroformat && typeof playerMicroformat.category === "string"
          ? playerMicroformat.category
          : undefined,
      thumbnailUrl: this.extractThumbnailUrl("thumbnail" in videoDetails ? videoDetails.thumbnail : undefined),
      live:
        ("isLiveContent" in videoDetails && typeof videoDetails.isLiveContent === "boolean"
          ? videoDetails.isLiveContent
          : undefined) ??
        (playerMicroformat && "isLive" in playerMicroformat && typeof playerMicroformat.isLive === "boolean"
          ? playerMicroformat.isLive
          : undefined),
    };
  }

  private extractSearchResults(response: Record<string, unknown>, limit: number): YouTubeSearchResultItem[] {
    const results: YouTubeSearchResultItem[] = [];
    this.walkForSearchResults(response, results, limit);
    return results;
  }

  private extractRelatedResults(
    response: Record<string, unknown>,
    targetVideoId: string,
    limit: number,
  ): YouTubeSearchResultItem[] {
    const results: YouTubeSearchResultItem[] = [];
    this.walkForRelatedResults(response, results, limit, targetVideoId);
    return results;
  }

  private walkForSearchResults(node: unknown, results: YouTubeSearchResultItem[], limit: number): void {
    if (results.length >= limit || node == null) {
      return;
    }

    if (Array.isArray(node)) {
      for (const entry of node) {
        this.walkForSearchResults(entry, results, limit);
        if (results.length >= limit) {
          return;
        }
      }
      return;
    }

    if (typeof node !== "object") {
      return;
    }

    if ("videoRenderer" in node) {
      const item = this.parseVideoSearchRenderer((node as { videoRenderer?: unknown }).videoRenderer);
      if (item) {
        results.push(item);
      }
      return;
    }

    for (const value of Object.values(node)) {
      this.walkForSearchResults(value, results, limit);
      if (results.length >= limit) {
        return;
      }
    }
  }

  private walkForRelatedResults(
    node: unknown,
    results: YouTubeSearchResultItem[],
    limit: number,
    targetVideoId: string,
  ): void {
    if (results.length >= limit || node == null) {
      return;
    }

    if (Array.isArray(node)) {
      for (const entry of node) {
        this.walkForRelatedResults(entry, results, limit, targetVideoId);
        if (results.length >= limit) {
          return;
        }
      }
      return;
    }

    if (typeof node !== "object") {
      return;
    }

    if ("compactVideoRenderer" in node) {
      const item = this.parseCompactVideoRenderer(
        (node as { compactVideoRenderer?: unknown }).compactVideoRenderer,
        targetVideoId,
      );
      if (item) {
        results.push(item);
      }
      return;
    }

    if ("lockupViewModel" in node) {
      const item = this.parseLockupViewModel((node as { lockupViewModel?: unknown }).lockupViewModel, targetVideoId);
      if (item) {
        results.push(item);
      }
      return;
    }

    for (const value of Object.values(node)) {
      this.walkForRelatedResults(value, results, limit, targetVideoId);
      if (results.length >= limit) {
        return;
      }
    }
  }

  private parseVideoSearchRenderer(renderer: unknown): YouTubeSearchResultItem | undefined {
    if (!renderer || typeof renderer !== "object" || !("videoId" in renderer) || typeof renderer.videoId !== "string") {
      return undefined;
    }

    const title = this.extractTextValue("title" in renderer ? renderer.title : undefined);
    if (!title) {
      return undefined;
    }

    const videoId = renderer.videoId;
    return {
      id: videoId,
      title,
      url: `${YOUTUBE_WATCH}${videoId}`,
      channel: this.extractTextValue(
        ("longBylineText" in renderer ? renderer.longBylineText : undefined) ??
          ("ownerText" in renderer ? renderer.ownerText : undefined),
      ),
      duration: this.extractTextValue("lengthText" in renderer ? renderer.lengthText : undefined),
      views: this.extractTextValue("viewCountText" in renderer ? renderer.viewCountText : undefined),
      published: this.extractTextValue("publishedTimeText" in renderer ? renderer.publishedTimeText : undefined),
      description: this.extractDescriptionValue(renderer),
      thumbnailUrl: this.extractThumbnailUrl("thumbnail" in renderer ? renderer.thumbnail : undefined),
    };
  }

  private parseCompactVideoRenderer(renderer: unknown, targetVideoId: string): YouTubeSearchResultItem | undefined {
    if (!renderer || typeof renderer !== "object" || !("videoId" in renderer) || typeof renderer.videoId !== "string") {
      return undefined;
    }

    if (renderer.videoId === targetVideoId) {
      return undefined;
    }

    const title = this.extractTextValue("title" in renderer ? renderer.title : undefined);
    if (!title) {
      return undefined;
    }

    return {
      id: renderer.videoId,
      title,
      url: `${YOUTUBE_WATCH}${renderer.videoId}`,
      channel: this.extractTextValue(
        ("longBylineText" in renderer ? renderer.longBylineText : undefined) ??
          ("shortBylineText" in renderer ? renderer.shortBylineText : undefined),
      ),
      duration: this.extractTextValue("lengthText" in renderer ? renderer.lengthText : undefined),
      views:
        this.extractTextValue("viewCountText" in renderer ? renderer.viewCountText : undefined) ??
        this.extractTextValue("shortViewCountText" in renderer ? renderer.shortViewCountText : undefined),
      published: this.extractTextValue("publishedTimeText" in renderer ? renderer.publishedTimeText : undefined),
      description: this.extractDescriptionValue(renderer as Record<string, unknown>),
      thumbnailUrl: this.extractThumbnailUrl("thumbnail" in renderer ? renderer.thumbnail : undefined),
    };
  }

  private parseLockupViewModel(renderer: unknown, targetVideoId: string): YouTubeSearchResultItem | undefined {
    if (
      !renderer ||
      typeof renderer !== "object" ||
      !("contentId" in renderer) ||
      typeof renderer.contentId !== "string" ||
      renderer.contentId === targetVideoId
    ) {
      return undefined;
    }

    const title = this.extractTextValueAtPath(renderer, ["metadata", "lockupMetadataViewModel", "title"]);
    if (!title) {
      return undefined;
    }

    const metadataRows = this.getNestedValue(renderer, [
      "metadata",
      "lockupMetadataViewModel",
      "metadata",
      "contentMetadataViewModel",
      "metadataRows",
    ]);
    const rowZeroParts = this.extractMetadataRowTexts(metadataRows, 0);
    const rowOneParts = this.extractMetadataRowTexts(metadataRows, 1);

    return {
      id: renderer.contentId,
      title,
      url: `${YOUTUBE_WATCH}${renderer.contentId}`,
      channel: rowZeroParts[0],
      views: rowOneParts[0],
      published: rowOneParts[1],
      duration: this.extractDurationFromLockup(renderer),
      thumbnailUrl: this.extractNestedThumbnailUrl("contentImage" in renderer ? renderer.contentImage : undefined),
    };
  }

  private extractPlaylistItems(initialData: Record<string, unknown>, limit: number): YouTubePlaylistItem[] {
    const items: YouTubePlaylistItem[] = [];
    this.walkForPlaylistItems(initialData, items, limit);
    return items;
  }

  private walkForPlaylistItems(node: unknown, items: YouTubePlaylistItem[], limit: number): void {
    if (items.length >= limit || node == null) {
      return;
    }

    if (Array.isArray(node)) {
      for (const entry of node) {
        this.walkForPlaylistItems(entry, items, limit);
        if (items.length >= limit) {
          return;
        }
      }
      return;
    }

    if (typeof node !== "object") {
      return;
    }

    if ("playlistVideoRenderer" in node) {
      const item = this.parsePlaylistVideoRenderer((node as { playlistVideoRenderer?: unknown }).playlistVideoRenderer);
      if (item) {
        items.push(item);
      }
      return;
    }

    for (const value of Object.values(node)) {
      this.walkForPlaylistItems(value, items, limit);
      if (items.length >= limit) {
        return;
      }
    }
  }

  private parsePlaylistVideoRenderer(renderer: unknown): YouTubePlaylistItem | undefined {
    if (!renderer || typeof renderer !== "object" || !("videoId" in renderer) || typeof renderer.videoId !== "string") {
      return undefined;
    }

    const title = this.extractTextValue("title" in renderer ? renderer.title : undefined);
    if (!title) {
      return undefined;
    }

    return {
      id: renderer.videoId,
      title,
      url: `${YOUTUBE_WATCH}${renderer.videoId}`,
      channel: this.extractTextValue(
        ("shortBylineText" in renderer ? renderer.shortBylineText : undefined) ??
          ("longBylineText" in renderer ? renderer.longBylineText : undefined),
      ),
      duration: this.extractTextValue("lengthText" in renderer ? renderer.lengthText : undefined),
      thumbnailUrl: this.extractThumbnailUrl("thumbnail" in renderer ? renderer.thumbnail : undefined),
    };
  }

  private extractDescriptionValue(renderer: Record<string, unknown>): string | undefined {
    const snippet =
      ("detailedMetadataSnippets" in renderer ? renderer.detailedMetadataSnippets : undefined) ??
      ("descriptionSnippet" in renderer ? renderer.descriptionSnippet : undefined);

    if (Array.isArray(snippet) && snippet[0] && typeof snippet[0] === "object") {
      return this.extractTextValue(
        "snippetText" in snippet[0] ? snippet[0].snippetText : "runs" in snippet[0] ? snippet[0] : undefined,
      );
    }

    return this.extractTextValue(snippet);
  }

  private extractThumbnailUrl(node: unknown): string | undefined {
    if (!node || typeof node !== "object" || !("thumbnails" in node) || !Array.isArray(node.thumbnails)) {
      return undefined;
    }

    const thumbnails = node.thumbnails.filter(
      (entry): entry is { url: string } => Boolean(entry && typeof entry === "object" && "url" in entry && typeof entry.url === "string"),
    );

    return thumbnails.at(-1)?.url;
  }

  private extractNestedThumbnailUrl(node: unknown): string | undefined {
    if (!node || typeof node !== "object") {
      return undefined;
    }

    if ("thumbnail" in node) {
      const direct = this.extractThumbnailUrl(node.thumbnail);
      if (direct) {
        return direct;
      }
    }

    for (const value of Object.values(node)) {
      const nested = this.extractNestedThumbnailUrl(value);
      if (nested) {
        return nested;
      }
    }

    return undefined;
  }

  private extractDurationFromLockup(renderer: Record<string, unknown>): string | undefined {
    return this.extractTextValueAtPath(renderer, [
      "contentImage",
      "thumbnailViewModel",
      "overlays",
      "0",
      "thumbnailBottomOverlayViewModel",
      "badges",
      "0",
      "thumbnailBadgeViewModel",
    ]);
  }

  private extractMetadataRowTexts(metadataRows: unknown, rowIndex: number): string[] {
    if (!Array.isArray(metadataRows) || !metadataRows[rowIndex] || typeof metadataRows[rowIndex] !== "object") {
      return [];
    }

    const row = metadataRows[rowIndex];
    const metadataParts =
      "metadataParts" in row && Array.isArray(row.metadataParts) ? row.metadataParts : [];

    return metadataParts
      .map((part: unknown) =>
        part && typeof part === "object" && "text" in part ? this.extractTextValue(part.text) : undefined,
      )
      .filter((value: string | undefined): value is string => typeof value === "string" && value.length > 0);
  }

  private extractTextValue(node: unknown): string | undefined {
    if (!node || typeof node !== "object") {
      return typeof node === "string" ? node : undefined;
    }

    if ("content" in node && typeof node.content === "string") {
      return node.content;
    }

    if ("simpleText" in node && typeof node.simpleText === "string") {
      return node.simpleText;
    }

    if ("runs" in node && Array.isArray(node.runs)) {
      const text = node.runs
        .map((entry) =>
          entry && typeof entry === "object" && "text" in entry && typeof entry.text === "string" ? entry.text : "",
        )
        .filter(Boolean)
        .join("");
      return text || undefined;
    }

    return undefined;
  }

  private extractTextValueAtPath(node: unknown, path: string[]): string | undefined {
    const target = this.getNestedValue(node, path);
    return this.extractTextValue(target);
  }

  private extractCaptionTracks(response: Record<string, unknown>): YouTubeCaptionTrack[] {
    const captions =
      "captions" in response && response.captions && typeof response.captions === "object" ? response.captions : undefined;
    const trackListRenderer =
      captions &&
      "playerCaptionsTracklistRenderer" in captions &&
      captions.playerCaptionsTracklistRenderer &&
      typeof captions.playerCaptionsTracklistRenderer === "object"
        ? captions.playerCaptionsTracklistRenderer
        : undefined;
    const captionTracks =
      trackListRenderer &&
      "captionTracks" in trackListRenderer &&
      Array.isArray(trackListRenderer.captionTracks)
        ? trackListRenderer.captionTracks
        : [];

    const tracks: YouTubeCaptionTrack[] = [];

    for (const track of captionTracks) {
      if (!track || typeof track !== "object") {
        continue;
      }

      const language =
        this.extractTextValue("name" in track ? track.name : undefined) ??
        ("languageCode" in track && typeof track.languageCode === "string" ? track.languageCode : undefined);
      const languageCode = "languageCode" in track && typeof track.languageCode === "string" ? track.languageCode : undefined;

      if (!language || !languageCode) {
        continue;
      }

      tracks.push({
        language,
        languageCode,
        kind: "kind" in track && typeof track.kind === "string" ? track.kind : undefined,
        autoGenerated: ("kind" in track && track.kind === "asr") || /\(auto-generated\)$/i.test(language),
        isTranslatable:
          "isTranslatable" in track && typeof track.isTranslatable === "boolean" ? track.isTranslatable : undefined,
      });
    }

    return tracks;
  }

  private extractAssignedJsonObject(html: string, variableName: string): Record<string, unknown> {
    const patterns = [`var ${variableName} = `, `${variableName} = `];
    for (const marker of patterns) {
      const markerIndex = html.indexOf(marker);
      if (markerIndex === -1) {
        continue;
      }

      const objectStart = html.indexOf("{", markerIndex + marker.length);
      if (objectStart === -1) {
        continue;
      }

      const objectText = this.readBalancedJsonObject(html, objectStart);
      if (!objectText) {
        continue;
      }

      return JSON.parse(objectText) as Record<string, unknown>;
    }

    throw new AutoCliError("YOUTUBE_PAGE_CONFIG_MISSING", `Missing ${variableName} from the YouTube page.`);
  }

  private readBalancedJsonObject(source: string, startIndex: number): string | undefined {
    let depth = 0;
    let inString = false;
    let escaped = false;

    for (let index = startIndex; index < source.length; index += 1) {
      const character = source[index];

      if (inString) {
        if (escaped) {
          escaped = false;
          continue;
        }

        if (character === "\\") {
          escaped = true;
          continue;
        }

        if (character === "\"") {
          inString = false;
        }

        continue;
      }

      if (character === "\"") {
        inString = true;
        continue;
      }

      if (character === "{") {
        depth += 1;
      } else if (character === "}") {
        depth -= 1;
        if (depth === 0) {
          return source.slice(startIndex, index + 1);
        }
      }
    }

    return undefined;
  }

  private findRenderer(node: unknown, rendererKey: string): Record<string, unknown> | undefined {
    if (!node || typeof node !== "object") {
      return undefined;
    }

    if (rendererKey in node) {
      const value = node[rendererKey as keyof typeof node];
      return value && typeof value === "object" ? (value as Record<string, unknown>) : undefined;
    }

    if (Array.isArray(node)) {
      for (const entry of node) {
        const nested = this.findRenderer(entry, rendererKey);
        if (nested) {
          return nested;
        }
      }
      return undefined;
    }

    for (const value of Object.values(node)) {
      const nested = this.findRenderer(value, rendererKey);
      if (nested) {
        return nested;
      }
    }

    return undefined;
  }

  private extractHandleFromUrl(url?: string): string | undefined {
    if (!url) {
      return undefined;
    }

    const match = url.match(/\/(@[A-Za-z0-9._-]+)/);
    return match?.[1];
  }

  private mapYouTubeWriteError(error: unknown, fallbackMessage: string): AutoCliError {
    if (
      isAutoCliError(error) &&
      (error.code === "YOUTUBE_REQUEST_REJECTED" ||
        error.code === "YOUTUBE_VIDEO_UNAVAILABLE" ||
        error.code === "YOUTUBE_VIDEO_INFO_MISSING")
    ) {
      return error;
    }

    if (isAutoCliError(error) && error.code === "HTTP_REQUEST_FAILED") {
      const status = typeof error.details?.status === "number" ? error.details.status : undefined;

      if (status === 400) {
        return new AutoCliError(
          "YOUTUBE_REQUEST_REJECTED",
          "YouTube rejected this action request. The video may not allow this action, or the saved cookies need a fresh export.",
          {
            cause: error,
            details: error.details,
          },
        );
      }

      if (status === 401 || status === 403) {
        return new AutoCliError(
          "SESSION_EXPIRED",
          "YouTube rejected the saved session for this action. Re-export cookies from an active browser session.",
          {
            cause: error,
            details: error.details,
          },
        );
      }
    }

    return new AutoCliError("PLATFORM_REQUEST_FAILED", fallbackMessage, {
      cause: error,
      details:
        isAutoCliError(error) && error.details
          ? error.details
          : error instanceof Error
            ? { message: error.message }
            : undefined,
    });
  }

  private async persistSessionState(session: PlatformSession, probe: YouTubeProbe): Promise<void> {
    await this.persistExistingSession(session, {
      user: session.user,
      status: probe.status,
      metadata: {
        ...(session.metadata ?? {}),
        ...(probe.metadata ?? {}),
      },
    });
  }

  private async filterYouTubeCookies(sourceJar: CookieJar): Promise<CookieJar> {
    const filteredJar = new CookieJar();
    const cookies = await sourceJar.getCookies(YOUTUBE_HOME);

    for (const cookie of cookies) {
      if (!YOUTUBE_COOKIE_ALLOWLIST.has(cookie.key)) {
        continue;
      }

      const normalized = Cookie.fromJSON(cookie.toJSON());
      if (!normalized) {
        continue;
      }

      await filteredJar.setCookie(normalized, `https://${cookie.domain}${cookie.path || "/"}`, {
        ignoreError: true,
      });
    }

    return filteredJar;
  }
}

function buildSapisidHash(sapisid: string, origin: string): string {
  const timestamp = Math.floor(Date.now() / 1_000);
  const digest = createHash("sha1").update(`${timestamp} ${sapisid} ${origin}`).digest("hex");
  return `SAPISIDHASH ${timestamp}_${digest}`;
}

function formatDuration(totalSeconds: number): string {
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  if (hours > 0) {
    return `${hours}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`;
  }

  return `${minutes}:${String(seconds).padStart(2, "0")}`;
}
