export const PLATFORM_NAMES = [
  "openstreetmap",
  "osrm",
  "anilist",
  "amazon",
  "cheat",
  "chatgpt",
  "claude",
  "crypto",
  "currency",
  "deepseek",
  "dns",
  "discordbot",
  "archive",
  "audio",
  "document",
  "ebay",
  "geo",
  "gif",
  "image",
  "etsy",
  "facebook",
  "flipkart",
  "gemini",
  "github",
  "githubbot",
  "gitlab",
  "grok",
  "headers",
  "ip",
  "imdb",
  "instagram",
  "justwatch",
  "kitsu",
  "markdown-fetch",
  "metadata",
  "myanimelist",
  "mistral",
  "news",
  "linkedin",
  "linear",
  "notion",
  "perplexity",
  "pdf",
  "qr",
  "qwen",
  "redirect",
  "screenshot",
  "robots",
  "rss",
  "sitemap",
  "slackbot",
  "ssl",
  "soundcloud",
  "spotify",
  "stocks",
  "zai",
  "telegrambot",
  "tiktok",
  "time",
  "translate",
  "uptime",
  "subtitle",
  "tvmaze",
  "video",
  "weather",
  "websearch",
  "whois",
  "x",
  "youtube",
  "youtube-music",
] as const;

export type PlatformName = (typeof PLATFORM_NAMES)[number];

export interface PlatformConfig {
  displayName: string;
  origin: string;
  homeUrl: string;
  cookieDomain: string;
  authCookieNames: readonly string[];
}

export const PLATFORM_CONFIG: Record<PlatformName, PlatformConfig> = {
  openstreetmap: {
    displayName: "OpenStreetMap",
    origin: "https://nominatim.openstreetmap.org",
    homeUrl: "https://www.openstreetmap.org/",
    cookieDomain: "openstreetmap.org",
    authCookieNames: [],
  },
  osrm: {
    displayName: "OSRM",
    origin: "https://router.project-osrm.org",
    homeUrl: "https://project-osrm.org/",
    cookieDomain: "project-osrm.org",
    authCookieNames: [],
  },
  anilist: {
    displayName: "AniList",
    origin: "https://graphql.anilist.co",
    homeUrl: "https://anilist.co/",
    cookieDomain: "anilist.co",
    authCookieNames: [],
  },
  amazon: {
    displayName: "Amazon",
    origin: "https://www.amazon.in",
    homeUrl: "https://www.amazon.in/",
    cookieDomain: "amazon.in",
    authCookieNames: ["at-main", "sess-at-main", "x-main"],
  },
  cheat: {
    displayName: "Cheat",
    origin: "https://cht.sh",
    homeUrl: "https://cht.sh/",
    cookieDomain: "cht.sh",
    authCookieNames: [],
  },
  chatgpt: {
    displayName: "ChatGPT",
    origin: "https://chatgpt.com",
    homeUrl: "https://chatgpt.com/",
    cookieDomain: "chatgpt.com",
    authCookieNames: ["__Secure-next-auth.session-token", "__Secure-authjs.session-token", "_puid"],
  },
  claude: {
    displayName: "Claude",
    origin: "https://claude.ai",
    homeUrl: "https://claude.ai/chats",
    cookieDomain: "claude.ai",
    authCookieNames: ["sessionKey"],
  },
  crypto: {
    displayName: "Crypto",
    origin: "https://api.coingecko.com",
    homeUrl: "https://www.coingecko.com/",
    cookieDomain: "coingecko.com",
    authCookieNames: [],
  },
  currency: {
    displayName: "Currency",
    origin: "https://open.er-api.com",
    homeUrl: "https://www.exchangerate-api.com/",
    cookieDomain: "exchangerate-api.com",
    authCookieNames: [],
  },
  deepseek: {
    displayName: "DeepSeek",
    origin: "https://chat.deepseek.com",
    homeUrl: "https://chat.deepseek.com/",
    cookieDomain: "deepseek.com",
    authCookieNames: [],
  },
  dns: {
    displayName: "DNS",
    origin: "https://dns.google",
    homeUrl: "https://dns.google/",
    cookieDomain: "dns.google",
    authCookieNames: [],
  },
  discordbot: {
    displayName: "Discord Bot",
    origin: "https://discord.com",
    homeUrl: "https://discord.com/developers/applications",
    cookieDomain: "discord.com",
    authCookieNames: [],
  },
  archive: {
    displayName: "Archive Editor",
    origin: "https://www.libarchive.org",
    homeUrl: "https://www.libarchive.org/",
    cookieDomain: "libarchive.org",
    authCookieNames: [],
  },
  audio: {
    displayName: "Audio Editor",
    origin: "https://ffmpeg.org",
    homeUrl: "https://ffmpeg.org/",
    cookieDomain: "ffmpeg.org",
    authCookieNames: [],
  },
  document: {
    displayName: "Document Editor",
    origin: "https://developer.apple.com",
    homeUrl: "https://developer.apple.com/",
    cookieDomain: "apple.com",
    authCookieNames: [],
  },
  ebay: {
    displayName: "eBay",
    origin: "https://www.ebay.com",
    homeUrl: "https://www.ebay.com/",
    cookieDomain: "ebay.com",
    authCookieNames: [],
  },
  geo: {
    displayName: "Geo",
    origin: "https://github.com/google/open-location-code",
    homeUrl: "https://github.com/google/open-location-code",
    cookieDomain: "github.com",
    authCookieNames: [],
  },
  gif: {
    displayName: "GIF Editor",
    origin: "https://ffmpeg.org",
    homeUrl: "https://ffmpeg.org/",
    cookieDomain: "ffmpeg.org",
    authCookieNames: [],
  },
  image: {
    displayName: "Image Editor",
    origin: "https://ffmpeg.org",
    homeUrl: "https://ffmpeg.org/",
    cookieDomain: "ffmpeg.org",
    authCookieNames: [],
  },
  etsy: {
    displayName: "Etsy",
    origin: "https://www.etsy.com",
    homeUrl: "https://www.etsy.com/",
    cookieDomain: "etsy.com",
    authCookieNames: [],
  },
  facebook: {
    displayName: "Facebook",
    origin: "https://www.facebook.com",
    homeUrl: "https://www.facebook.com/",
    cookieDomain: "facebook.com",
    authCookieNames: ["c_user", "xs"],
  },
  flipkart: {
    displayName: "Flipkart",
    origin: "https://www.flipkart.com",
    homeUrl: "https://www.flipkart.com/",
    cookieDomain: "flipkart.com",
    authCookieNames: ["T", "AT"],
  },
  gemini: {
    displayName: "Gemini",
    origin: "https://gemini.google.com",
    homeUrl: "https://gemini.google.com/",
    cookieDomain: "google.com",
    authCookieNames: ["__Secure-1PSID", "__Secure-1PSIDTS"],
  },
  github: {
    displayName: "GitHub",
    origin: "https://api.github.com",
    homeUrl: "https://github.com/",
    cookieDomain: "github.com",
    authCookieNames: [],
  },
  githubbot: {
    displayName: "GitHub Bot",
    origin: "https://api.github.com",
    homeUrl: "https://github.com/",
    cookieDomain: "github.com",
    authCookieNames: [],
  },
  gitlab: {
    displayName: "GitLab",
    origin: "https://gitlab.com",
    homeUrl: "https://gitlab.com/",
    cookieDomain: "gitlab.com",
    authCookieNames: [],
  },
  grok: {
    displayName: "Grok",
    origin: "https://grok.com",
    homeUrl: "https://grok.com/",
    cookieDomain: "grok.com",
    authCookieNames: ["sso", "sso-rw", "x-userid"],
  },
  headers: {
    displayName: "Headers",
    origin: "https://example.com",
    homeUrl: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers",
    cookieDomain: "example.com",
    authCookieNames: [],
  },
  ip: {
    displayName: "IP",
    origin: "https://api64.ipify.org",
    homeUrl: "https://www.ipify.org/",
    cookieDomain: "ipify.org",
    authCookieNames: [],
  },
  imdb: {
    displayName: "IMDb",
    origin: "https://www.imdb.com",
    homeUrl: "https://www.imdb.com/",
    cookieDomain: "imdb.com",
    authCookieNames: [],
  },
  instagram: {
    displayName: "Instagram",
    origin: "https://www.instagram.com",
    homeUrl: "https://www.instagram.com/",
    cookieDomain: "instagram.com",
    authCookieNames: ["sessionid", "csrftoken", "ds_user_id"],
  },
  justwatch: {
    displayName: "JustWatch",
    origin: "https://www.justwatch.com",
    homeUrl: "https://www.justwatch.com/",
    cookieDomain: "justwatch.com",
    authCookieNames: [],
  },
  kitsu: {
    displayName: "Kitsu",
    origin: "https://kitsu.io",
    homeUrl: "https://kitsu.io/",
    cookieDomain: "kitsu.io",
    authCookieNames: [],
  },
  "markdown-fetch": {
    displayName: "Markdown Fetch",
    origin: "https://example.com",
    homeUrl: "https://example.com/",
    cookieDomain: "example.com",
    authCookieNames: [],
  },
  metadata: {
    displayName: "Metadata",
    origin: "https://example.com",
    homeUrl: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta",
    cookieDomain: "example.com",
    authCookieNames: [],
  },
  myanimelist: {
    displayName: "MyAnimeList",
    origin: "https://myanimelist.net",
    homeUrl: "https://myanimelist.net/",
    cookieDomain: "myanimelist.net",
    authCookieNames: ["MALHLOGSESSID", "MALSESSIONID", "is_logged_in"],
  },
  mistral: {
    displayName: "Mistral",
    origin: "https://chat.mistral.ai",
    homeUrl: "https://chat.mistral.ai/",
    cookieDomain: "mistral.ai",
    authCookieNames: ["ory_session_*"],
  },
  news: {
    displayName: "News",
    origin: "https://news.google.com",
    homeUrl: "https://news.google.com/",
    cookieDomain: "news.google.com",
    authCookieNames: [],
  },
  linkedin: {
    displayName: "LinkedIn",
    origin: "https://www.linkedin.com",
    homeUrl: "https://www.linkedin.com/",
    cookieDomain: "linkedin.com",
    authCookieNames: ["li_at", "JSESSIONID"],
  },
  linear: {
    displayName: "Linear",
    origin: "https://api.linear.app",
    homeUrl: "https://linear.app/",
    cookieDomain: "linear.app",
    authCookieNames: [],
  },
  notion: {
    displayName: "Notion",
    origin: "https://api.notion.com",
    homeUrl: "https://www.notion.so/",
    cookieDomain: "notion.so",
    authCookieNames: [],
  },
  perplexity: {
    displayName: "Perplexity",
    origin: "https://www.perplexity.ai",
    homeUrl: "https://www.perplexity.ai/",
    cookieDomain: "perplexity.ai",
    authCookieNames: ["__Secure-next-auth.session-token", "next-auth.session-token"],
  },
  pdf: {
    displayName: "PDF Editor",
    origin: "https://qpdf.readthedocs.io",
    homeUrl: "https://qpdf.readthedocs.io/",
    cookieDomain: "qpdf.readthedocs.io",
    authCookieNames: [],
  },
  qr: {
    displayName: "QR",
    origin: "https://qrenco.de",
    homeUrl: "https://qrenco.de/",
    cookieDomain: "qrenco.de",
    authCookieNames: [],
  },
  screenshot: {
    displayName: "Screenshot",
    origin: "https://api.microlink.io",
    homeUrl: "https://microlink.io/",
    cookieDomain: "microlink.io",
    authCookieNames: [],
  },
  qwen: {
    displayName: "Qwen",
    origin: "https://chat.qwen.ai",
    homeUrl: "https://chat.qwen.ai/",
    cookieDomain: "qwen.ai",
    authCookieNames: ["token"],
  },
  redirect: {
    displayName: "Redirect",
    origin: "https://example.com",
    homeUrl: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections",
    cookieDomain: "example.com",
    authCookieNames: [],
  },
  robots: {
    displayName: "Robots",
    origin: "https://www.rfc-editor.org",
    homeUrl: "https://www.rfc-editor.org/rfc/rfc9309",
    cookieDomain: "rfc-editor.org",
    authCookieNames: [],
  },
  rss: {
    displayName: "RSS",
    origin: "https://hnrss.org",
    homeUrl: "https://hnrss.org/",
    cookieDomain: "hnrss.org",
    authCookieNames: [],
  },
  sitemap: {
    displayName: "Sitemap",
    origin: "https://www.sitemaps.org",
    homeUrl: "https://www.sitemaps.org/",
    cookieDomain: "sitemaps.org",
    authCookieNames: [],
  },
  slackbot: {
    displayName: "Slack Bot",
    origin: "https://slack.com",
    homeUrl: "https://api.slack.com",
    cookieDomain: "slack.com",
    authCookieNames: [],
  },
  ssl: {
    displayName: "SSL",
    origin: "https://developer.mozilla.org",
    homeUrl: "https://developer.mozilla.org/en-US/docs/Web/Security/Transport_Layer_Security",
    cookieDomain: "developer.mozilla.org",
    authCookieNames: [],
  },
  soundcloud: {
    displayName: "SoundCloud",
    origin: "https://api-v2.soundcloud.com",
    homeUrl: "https://soundcloud.com/",
    cookieDomain: "soundcloud.com",
    authCookieNames: [],
  },
  spotify: {
    displayName: "Spotify",
    origin: "https://open.spotify.com",
    homeUrl: "https://open.spotify.com/",
    cookieDomain: "spotify.com",
    authCookieNames: ["sp_dc", "sp_key"],
  },
  stocks: {
    displayName: "Stocks",
    origin: "https://stooq.com",
    homeUrl: "https://stooq.com/",
    cookieDomain: "stooq.com",
    authCookieNames: [],
  },
  zai: {
    displayName: "Z.ai",
    origin: "https://chat.z.ai",
    homeUrl: "https://chat.z.ai/",
    cookieDomain: "z.ai",
    authCookieNames: ["token"],
  },
  telegrambot: {
    displayName: "Telegram Bot",
    origin: "https://api.telegram.org",
    homeUrl: "https://core.telegram.org/bots/api",
    cookieDomain: "telegram.org",
    authCookieNames: [],
  },
  tiktok: {
    displayName: "TikTok",
    origin: "https://www.tiktok.com",
    homeUrl: "https://www.tiktok.com/",
    cookieDomain: "tiktok.com",
    authCookieNames: ["sid_tt"],
  },
  time: {
    displayName: "Time",
    origin: "https://worldtimeapi.org",
    homeUrl: "https://worldtimeapi.org/",
    cookieDomain: "worldtimeapi.org",
    authCookieNames: [],
  },
  translate: {
    displayName: "Translate",
    origin: "https://translate.googleapis.com",
    homeUrl: "https://translate.google.com/",
    cookieDomain: "googleapis.com",
    authCookieNames: [],
  },
  uptime: {
    displayName: "Uptime",
    origin: "https://example.com",
    homeUrl: "https://example.com/",
    cookieDomain: "example.com",
    authCookieNames: [],
  },
  subtitle: {
    displayName: "Subtitle Editor",
    origin: "https://ffmpeg.org",
    homeUrl: "https://ffmpeg.org/",
    cookieDomain: "ffmpeg.org",
    authCookieNames: [],
  },
  tvmaze: {
    displayName: "TVMaze",
    origin: "https://api.tvmaze.com",
    homeUrl: "https://www.tvmaze.com/",
    cookieDomain: "tvmaze.com",
    authCookieNames: [],
  },
  video: {
    displayName: "Video Editor",
    origin: "https://ffmpeg.org",
    homeUrl: "https://ffmpeg.org/",
    cookieDomain: "ffmpeg.org",
    authCookieNames: [],
  },
  weather: {
    displayName: "Weather",
    origin: "https://wttr.in",
    homeUrl: "https://wttr.in/",
    cookieDomain: "wttr.in",
    authCookieNames: [],
  },
  websearch: {
    displayName: "Web Search",
    origin: "https://html.duckduckgo.com",
    homeUrl: "https://duckduckgo.com/",
    cookieDomain: "duckduckgo.com",
    authCookieNames: [],
  },
  whois: {
    displayName: "Whois",
    origin: "https://rdap.org",
    homeUrl: "https://rdap.org/",
    cookieDomain: "rdap.org",
    authCookieNames: [],
  },
  x: {
    displayName: "X",
    origin: "https://x.com",
    homeUrl: "https://x.com/",
    cookieDomain: "x.com",
    authCookieNames: ["auth_token", "ct0"],
  },
  youtube: {
    displayName: "YouTube",
    origin: "https://www.youtube.com",
    homeUrl: "https://www.youtube.com/",
    cookieDomain: "youtube.com",
    authCookieNames: ["SAPISID", "LOGIN_INFO", "__Secure-3PSID", "SSID"],
  },
  "youtube-music": {
    displayName: "YouTube Music",
    origin: "https://music.youtube.com",
    homeUrl: "https://music.youtube.com/",
    cookieDomain: "youtube.com",
    authCookieNames: ["SAPISID", "LOGIN_INFO", "__Secure-3PSID", "SSID"],
  },
};

export function isPlatform(value: string): value is PlatformName {
  return (PLATFORM_NAMES as readonly string[]).includes(value);
}

export function getPlatformConfig(platform: PlatformName): PlatformConfig {
  return PLATFORM_CONFIG[platform];
}

export function getPlatformDisplayName(platform: PlatformName): string {
  return getPlatformConfig(platform).displayName;
}

export function getPlatformOrigin(platform: PlatformName): string {
  return getPlatformConfig(platform).origin;
}

export function getPlatformHomeUrl(platform: PlatformName): string {
  return getPlatformConfig(platform).homeUrl;
}

export function getPlatformCookieDomain(platform: PlatformName): string {
  return getPlatformConfig(platform).cookieDomain;
}

export function getPlatformAuthCookieNames(platform: PlatformName): readonly string[] {
  return getPlatformConfig(platform).authCookieNames;
}
