export const PLATFORM_NAMES = [
  "openstreetmap",
  "osrm",
  "anilist",
  "amazon",
  "bandcamp",
  "bluesky",
  "cheat",
  "chatgpt",
  "claude",
  "cloudflare",
  "confluence",
  "crypto",
  "currency",
  "deepseek",
  "deezer",
  "digitalocean",
  "json",
  "csv",
  "download",
  "dns",
  "discordbot",
  "archive",
  "audio",
  "document",
  "ebay",
  "favicon",
  "geo",
  "gif",
  "image",
  "etsy",
  "facebook",
  "flipkart",
  "fly",
  "gemini",
  "github",
  "githubbot",
  "gitlab",
  "grok",
  "http",
  "headers",
  "html",
  "ip",
  "imdb",
  "instagram",
  "jira",
  "justwatch",
  "letterboxd",
  "kitsu",
  "markdown",
  "markdown-fetch",
  "mastodon",
  "metadata",
  "myanimelist",
  "mistral",
  "news",
  "netlify",
  "oembed",
  "page-links",
  "linkedin",
  "linear",
  "notion",
  "perplexity",
  "pdf",
  "pinterest",
  "qr",
  "qwen",
  "railway",
  "reddit",
  "redirect",
  "render",
  "screenshot",
  "robots",
  "rss",
  "sitemap",
  "slackbot",
  "ssl",
  "soundcloud",
  "spotify",
  "stocks",
  "zai",
  "telegram",
  "telegrambot",
  "threads",
  "tiktok",
  "time",
  "timezone",
  "transcript",
  "translate",
  "uptime",
  "uptimerobot",
  "subtitle",
  "supabase",
  "text",
  "trello",
  "tmdb",
  "tvmaze",
  "vercel",
  "video",
  "weather",
  "websearch",
  "whatsapp",
  "whois",
  "x",
  "xml",
  "yaml",
  "youtube",
  "youtube-music",
] as const;

export type PlatformName = (typeof PLATFORM_NAMES)[number];

export interface PlatformConfig {
  displayName: string;
  origin: string;
  homeUrl: string;
  cookieDomain: string;
  authCookieNames: readonly string[];
  browserAuthCookieNames?: readonly string[];
  browserAuthStorageKeys?: readonly string[];
}

export const PLATFORM_CONFIG: Record<PlatformName, PlatformConfig> = {
  openstreetmap: {
    displayName: "OpenStreetMap",
    origin: "https://nominatim.openstreetmap.org",
    homeUrl: "https://www.openstreetmap.org/",
    cookieDomain: "openstreetmap.org",
    authCookieNames: [],
  },
  osrm: {
    displayName: "OSRM",
    origin: "https://router.project-osrm.org",
    homeUrl: "https://project-osrm.org/",
    cookieDomain: "project-osrm.org",
    authCookieNames: [],
  },
  anilist: {
    displayName: "AniList",
    origin: "https://graphql.anilist.co",
    homeUrl: "https://anilist.co/",
    cookieDomain: "anilist.co",
    authCookieNames: [],
  },
  amazon: {
    displayName: "Amazon",
    origin: "https://www.amazon.in",
    homeUrl: "https://www.amazon.in/",
    cookieDomain: "amazon.in",
    authCookieNames: ["at-main", "sess-at-main", "x-main"],
  },
  bandcamp: {
    displayName: "Bandcamp",
    origin: "https://bandcamp.com",
    homeUrl: "https://bandcamp.com/",
    cookieDomain: "bandcamp.com",
    authCookieNames: [],
  },
  bluesky: {
    displayName: "Bluesky",
    origin: "https://public.api.bsky.app",
    homeUrl: "https://bsky.app/",
    cookieDomain: "bsky.app",
    authCookieNames: [],
  },
  cheat: {
    displayName: "Cheat",
    origin: "https://cht.sh",
    homeUrl: "https://cht.sh/",
    cookieDomain: "cht.sh",
    authCookieNames: [],
  },
  chatgpt: {
    displayName: "ChatGPT",
    origin: "https://chatgpt.com",
    homeUrl: "https://chatgpt.com/",
    cookieDomain: "chatgpt.com",
    authCookieNames: ["__Secure-next-auth.session-token", "__Secure-authjs.session-token", "_puid"],
  },
  claude: {
    displayName: "Claude",
    origin: "https://claude.ai",
    homeUrl: "https://claude.ai/chats",
    cookieDomain: "claude.ai",
    authCookieNames: ["sessionKey"],
  },
  cloudflare: {
    displayName: "Cloudflare",
    origin: "https://api.cloudflare.com/client/v4",
    homeUrl: "https://dash.cloudflare.com/",
    cookieDomain: "cloudflare.com",
    authCookieNames: [],
  },
  confluence: {
    displayName: "Confluence",
    origin: "https://www.atlassian.com/software/confluence",
    homeUrl: "https://www.atlassian.com/software/confluence",
    cookieDomain: "atlassian.net",
    authCookieNames: ["cloud.session.token", "tenant.session.token", "atlassian.xsrf.token"],
    browserAuthCookieNames: ["cloud.session.token", "tenant.session.token"],
  },
  crypto: {
    displayName: "Crypto",
    origin: "https://api.coingecko.com",
    homeUrl: "https://www.coingecko.com/",
    cookieDomain: "coingecko.com",
    authCookieNames: [],
  },
  currency: {
    displayName: "Currency",
    origin: "https://open.er-api.com",
    homeUrl: "https://www.exchangerate-api.com/",
    cookieDomain: "exchangerate-api.com",
    authCookieNames: [],
  },
  deepseek: {
    displayName: "DeepSeek",
    origin: "https://chat.deepseek.com",
    homeUrl: "https://chat.deepseek.com/",
    cookieDomain: "deepseek.com",
    authCookieNames: [],
    browserAuthStorageKeys: ["userToken", "authToken", "token"],
  },
  deezer: {
    displayName: "Deezer",
    origin: "https://api.deezer.com",
    homeUrl: "https://www.deezer.com/",
    cookieDomain: "deezer.com",
    authCookieNames: [],
  },
  digitalocean: {
    displayName: "DigitalOcean",
    origin: "https://api.digitalocean.com/v2",
    homeUrl: "https://cloud.digitalocean.com/",
    cookieDomain: "digitalocean.com",
    authCookieNames: [],
  },
  json: {
    displayName: "JSON",
    origin: "https://www.json.org",
    homeUrl: "https://www.json.org/json-en.html",
    cookieDomain: "json.org",
    authCookieNames: [],
  },
  csv: {
    displayName: "CSV",
    origin: "https://datatracker.ietf.org",
    homeUrl: "https://datatracker.ietf.org/doc/html/rfc4180",
    cookieDomain: "ietf.org",
    authCookieNames: [],
  },
  download: {
    displayName: "Download",
    origin: "https://github.com/yt-dlp/yt-dlp",
    homeUrl: "https://github.com/yt-dlp/yt-dlp",
    cookieDomain: "yt-dlp.github.io",
    authCookieNames: [],
  },
  dns: {
    displayName: "DNS",
    origin: "https://dns.google",
    homeUrl: "https://dns.google/",
    cookieDomain: "dns.google",
    authCookieNames: [],
  },
  discordbot: {
    displayName: "Discord Bot",
    origin: "https://discord.com",
    homeUrl: "https://discord.com/developers/applications",
    cookieDomain: "discord.com",
    authCookieNames: [],
  },
  archive: {
    displayName: "Archive Editor",
    origin: "https://www.libarchive.org",
    homeUrl: "https://www.libarchive.org/",
    cookieDomain: "libarchive.org",
    authCookieNames: [],
  },
  audio: {
    displayName: "Audio Editor",
    origin: "https://ffmpeg.org",
    homeUrl: "https://ffmpeg.org/",
    cookieDomain: "ffmpeg.org",
    authCookieNames: [],
  },
  document: {
    displayName: "Document Editor",
    origin: "https://developer.apple.com",
    homeUrl: "https://developer.apple.com/",
    cookieDomain: "apple.com",
    authCookieNames: [],
  },
  ebay: {
    displayName: "eBay",
    origin: "https://www.ebay.com",
    homeUrl: "https://www.ebay.com/",
    cookieDomain: "ebay.com",
    authCookieNames: [],
  },
  favicon: {
    displayName: "Favicon",
    origin: "https://example.com",
    homeUrl: "https://developer.mozilla.org/en-US/docs/Glossary/Favicon",
    cookieDomain: "example.com",
    authCookieNames: [],
  },
  geo: {
    displayName: "Geo",
    origin: "https://github.com/google/open-location-code",
    homeUrl: "https://github.com/google/open-location-code",
    cookieDomain: "github.com",
    authCookieNames: [],
  },
  gif: {
    displayName: "GIF Editor",
    origin: "https://ffmpeg.org",
    homeUrl: "https://ffmpeg.org/",
    cookieDomain: "ffmpeg.org",
    authCookieNames: [],
  },
  image: {
    displayName: "Image Editor",
    origin: "https://ffmpeg.org",
    homeUrl: "https://ffmpeg.org/",
    cookieDomain: "ffmpeg.org",
    authCookieNames: [],
  },
  etsy: {
    displayName: "Etsy",
    origin: "https://www.etsy.com",
    homeUrl: "https://www.etsy.com/",
    cookieDomain: "etsy.com",
    authCookieNames: [],
  },
  facebook: {
    displayName: "Facebook",
    origin: "https://www.facebook.com",
    homeUrl: "https://www.facebook.com/",
    cookieDomain: "facebook.com",
    authCookieNames: ["c_user", "xs"],
  },
  flipkart: {
    displayName: "Flipkart",
    origin: "https://www.flipkart.com",
    homeUrl: "https://www.flipkart.com/",
    cookieDomain: "flipkart.com",
    authCookieNames: ["T", "AT"],
  },
  fly: {
    displayName: "Fly.io",
    origin: "https://api.machines.dev",
    homeUrl: "https://fly.io/dashboard",
    cookieDomain: "fly.io",
    authCookieNames: [],
  },
  gemini: {
    displayName: "Gemini",
    origin: "https://gemini.google.com",
    homeUrl: "https://gemini.google.com/",
    cookieDomain: "google.com",
    authCookieNames: ["__Secure-1PSID", "__Secure-1PSIDTS"],
  },
  github: {
    displayName: "GitHub",
    origin: "https://github.com",
    homeUrl: "https://github.com/",
    cookieDomain: "github.com",
    authCookieNames: ["user_session", "_gh_sess", "logged_in"],
    browserAuthCookieNames: ["user_session", "logged_in"],
  },
  githubbot: {
    displayName: "GitHub Bot",
    origin: "https://api.github.com",
    homeUrl: "https://github.com/",
    cookieDomain: "github.com",
    authCookieNames: [],
  },
  gitlab: {
    displayName: "GitLab",
    origin: "https://gitlab.com",
    homeUrl: "https://gitlab.com/",
    cookieDomain: "gitlab.com",
    authCookieNames: ["_gitlab_session", "remember_user_token"],
  },
  grok: {
    displayName: "Grok",
    origin: "https://grok.com",
    homeUrl: "https://grok.com/",
    cookieDomain: "grok.com",
    authCookieNames: ["sso", "sso-rw", "x-userid"],
  },
  http: {
    displayName: "HTTP Toolkit",
    origin: "https://developer.mozilla.org",
    homeUrl: "https://developer.mozilla.org/en-US/docs/Web/HTTP",
    cookieDomain: "developer.mozilla.org",
    authCookieNames: [],
  },
  headers: {
    displayName: "Headers",
    origin: "https://example.com",
    homeUrl: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers",
    cookieDomain: "example.com",
    authCookieNames: [],
  },
  html: {
    displayName: "HTML",
    origin: "https://html.spec.whatwg.org",
    homeUrl: "https://html.spec.whatwg.org/",
    cookieDomain: "whatwg.org",
    authCookieNames: [],
  },
  ip: {
    displayName: "IP",
    origin: "https://api64.ipify.org",
    homeUrl: "https://www.ipify.org/",
    cookieDomain: "ipify.org",
    authCookieNames: [],
  },
  imdb: {
    displayName: "IMDb",
    origin: "https://www.imdb.com",
    homeUrl: "https://www.imdb.com/",
    cookieDomain: "imdb.com",
    authCookieNames: [],
  },
  instagram: {
    displayName: "Instagram",
    origin: "https://www.instagram.com",
    homeUrl: "https://www.instagram.com/",
    cookieDomain: "instagram.com",
    authCookieNames: ["sessionid", "csrftoken", "ds_user_id"],
    browserAuthCookieNames: ["sessionid", "ds_user_id"],
  },
  jira: {
    displayName: "Jira",
    origin: "https://www.atlassian.com/software/jira",
    homeUrl: "https://www.atlassian.com/software/jira",
    cookieDomain: "atlassian.net",
    authCookieNames: ["cloud.session.token", "tenant.session.token", "atlassian.xsrf.token"],
    browserAuthCookieNames: ["cloud.session.token", "tenant.session.token"],
  },
  justwatch: {
    displayName: "JustWatch",
    origin: "https://www.justwatch.com",
    homeUrl: "https://www.justwatch.com/",
    cookieDomain: "justwatch.com",
    authCookieNames: [],
  },
  letterboxd: {
    displayName: "Letterboxd",
    origin: "https://letterboxd.com",
    homeUrl: "https://letterboxd.com/",
    cookieDomain: "letterboxd.com",
    authCookieNames: [],
  },
  markdown: {
    displayName: "Markdown",
    origin: "https://commonmark.org",
    homeUrl: "https://commonmark.org/",
    cookieDomain: "commonmark.org",
    authCookieNames: [],
  },
  kitsu: {
    displayName: "Kitsu",
    origin: "https://kitsu.io",
    homeUrl: "https://kitsu.io/",
    cookieDomain: "kitsu.io",
    authCookieNames: [],
  },
  "markdown-fetch": {
    displayName: "Markdown Fetch",
    origin: "https://example.com",
    homeUrl: "https://example.com/",
    cookieDomain: "example.com",
    authCookieNames: [],
  },
  mastodon: {
    displayName: "Mastodon",
    origin: "https://mastodon.social",
    homeUrl: "https://mastodon.social/",
    cookieDomain: "mastodon.social",
    authCookieNames: [],
  },
  metadata: {
    displayName: "Metadata",
    origin: "https://example.com",
    homeUrl: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta",
    cookieDomain: "example.com",
    authCookieNames: [],
  },
  myanimelist: {
    displayName: "MyAnimeList",
    origin: "https://myanimelist.net",
    homeUrl: "https://myanimelist.net/",
    cookieDomain: "myanimelist.net",
    authCookieNames: ["MALHLOGSESSID", "MALSESSIONID", "is_logged_in"],
  },
  mistral: {
    displayName: "Mistral",
    origin: "https://chat.mistral.ai",
    homeUrl: "https://chat.mistral.ai/",
    cookieDomain: "mistral.ai",
    authCookieNames: ["ory_session_*"],
  },
  news: {
    displayName: "News",
    origin: "https://news.google.com",
    homeUrl: "https://news.google.com/",
    cookieDomain: "news.google.com",
    authCookieNames: [],
  },
  netlify: {
    displayName: "Netlify",
    origin: "https://api.netlify.com/api/v1",
    homeUrl: "https://app.netlify.com/",
    cookieDomain: "netlify.com",
    authCookieNames: [],
  },
  oembed: {
    displayName: "oEmbed",
    origin: "https://noembed.com",
    homeUrl: "https://oembed.com/",
    cookieDomain: "noembed.com",
    authCookieNames: [],
  },
  "page-links": {
    displayName: "Page Links",
    origin: "https://example.com",
    homeUrl: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a",
    cookieDomain: "example.com",
    authCookieNames: [],
  },
  linkedin: {
    displayName: "LinkedIn",
    origin: "https://www.linkedin.com",
    homeUrl: "https://www.linkedin.com/",
    cookieDomain: "linkedin.com",
    authCookieNames: ["li_at", "JSESSIONID"],
    browserAuthCookieNames: ["li_at"],
  },
  linear: {
    displayName: "Linear",
    origin: "https://api.linear.app",
    homeUrl: "https://linear.app/",
    cookieDomain: "linear.app",
    authCookieNames: ["linear_session", "__Host-linear_session"],
  },
  notion: {
    displayName: "Notion",
    origin: "https://www.notion.so",
    homeUrl: "https://www.notion.so/",
    cookieDomain: "notion.so",
    authCookieNames: ["token_v2", "notion_user_id"],
    browserAuthCookieNames: ["token_v2"],
  },
  perplexity: {
    displayName: "Perplexity",
    origin: "https://www.perplexity.ai",
    homeUrl: "https://www.perplexity.ai/",
    cookieDomain: "perplexity.ai",
    authCookieNames: ["__Secure-next-auth.session-token", "next-auth.session-token"],
  },
  pdf: {
    displayName: "PDF Editor",
    origin: "https://qpdf.readthedocs.io",
    homeUrl: "https://qpdf.readthedocs.io/",
    cookieDomain: "qpdf.readthedocs.io",
    authCookieNames: [],
  },
  pinterest: {
    displayName: "Pinterest",
    origin: "https://www.pinterest.com",
    homeUrl: "https://www.pinterest.com/",
    cookieDomain: "pinterest.com",
    authCookieNames: [],
  },
  qr: {
    displayName: "QR",
    origin: "https://qrenco.de",
    homeUrl: "https://qrenco.de/",
    cookieDomain: "qrenco.de",
    authCookieNames: [],
  },
  screenshot: {
    displayName: "Screenshot",
    origin: "https://api.microlink.io",
    homeUrl: "https://microlink.io/",
    cookieDomain: "microlink.io",
    authCookieNames: [],
  },
  qwen: {
    displayName: "Qwen",
    origin: "https://chat.qwen.ai",
    homeUrl: "https://chat.qwen.ai/",
    cookieDomain: "qwen.ai",
    authCookieNames: ["token"],
  },
  railway: {
    displayName: "Railway",
    origin: "https://backboard.railway.app/graphql/v2",
    homeUrl: "https://railway.com/",
    cookieDomain: "railway.app",
    authCookieNames: [],
  },
  reddit: {
    displayName: "Reddit",
    origin: "https://www.reddit.com",
    homeUrl: "https://www.reddit.com/",
    cookieDomain: "reddit.com",
    authCookieNames: ["reddit_session", "token_v2"],
    browserAuthCookieNames: ["reddit_session", "token_v2"],
  },
  redirect: {
    displayName: "Redirect",
    origin: "https://example.com",
    homeUrl: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections",
    cookieDomain: "example.com",
    authCookieNames: [],
  },
  render: {
    displayName: "Render",
    origin: "https://api.render.com/v1",
    homeUrl: "https://dashboard.render.com/",
    cookieDomain: "render.com",
    authCookieNames: [],
  },
  robots: {
    displayName: "Robots",
    origin: "https://www.rfc-editor.org",
    homeUrl: "https://www.rfc-editor.org/rfc/rfc9309",
    cookieDomain: "rfc-editor.org",
    authCookieNames: [],
  },
  rss: {
    displayName: "RSS",
    origin: "https://hnrss.org",
    homeUrl: "https://hnrss.org/",
    cookieDomain: "hnrss.org",
    authCookieNames: [],
  },
  sitemap: {
    displayName: "Sitemap",
    origin: "https://www.sitemaps.org",
    homeUrl: "https://www.sitemaps.org/",
    cookieDomain: "sitemaps.org",
    authCookieNames: [],
  },
  slackbot: {
    displayName: "Slack Bot",
    origin: "https://slack.com",
    homeUrl: "https://api.slack.com",
    cookieDomain: "slack.com",
    authCookieNames: [],
  },
  ssl: {
    displayName: "SSL",
    origin: "https://developer.mozilla.org",
    homeUrl: "https://developer.mozilla.org/en-US/docs/Web/Security/Transport_Layer_Security",
    cookieDomain: "developer.mozilla.org",
    authCookieNames: [],
  },
  soundcloud: {
    displayName: "SoundCloud",
    origin: "https://api-v2.soundcloud.com",
    homeUrl: "https://soundcloud.com/",
    cookieDomain: "soundcloud.com",
    authCookieNames: [],
  },
  spotify: {
    displayName: "Spotify",
    origin: "https://open.spotify.com",
    homeUrl: "https://open.spotify.com/",
    cookieDomain: "spotify.com",
    authCookieNames: ["sp_dc", "sp_key"],
  },
  stocks: {
    displayName: "Stocks",
    origin: "https://stooq.com",
    homeUrl: "https://stooq.com/",
    cookieDomain: "stooq.com",
    authCookieNames: [],
  },
  zai: {
    displayName: "Z.ai",
    origin: "https://chat.z.ai",
    homeUrl: "https://chat.z.ai/",
    cookieDomain: "z.ai",
    authCookieNames: ["token"],
  },
  telegram: {
    displayName: "Telegram",
    origin: "https://web.telegram.org",
    homeUrl: "https://web.telegram.org/",
    cookieDomain: "telegram.org",
    authCookieNames: [],
  },
  telegrambot: {
    displayName: "Telegram Bot",
    origin: "https://api.telegram.org",
    homeUrl: "https://core.telegram.org/bots/api",
    cookieDomain: "telegram.org",
    authCookieNames: [],
  },
  threads: {
    displayName: "Threads",
    origin: "https://www.threads.net",
    homeUrl: "https://www.threads.net/",
    cookieDomain: "threads.net",
    authCookieNames: [],
  },
  tiktok: {
    displayName: "TikTok",
    origin: "https://www.tiktok.com",
    homeUrl: "https://www.tiktok.com/",
    cookieDomain: "tiktok.com",
    authCookieNames: ["sid_tt"],
  },
  time: {
    displayName: "Time",
    origin: "https://worldtimeapi.org",
    homeUrl: "https://worldtimeapi.org/",
    cookieDomain: "worldtimeapi.org",
    authCookieNames: [],
  },
  timezone: {
    displayName: "Timezone",
    origin: "https://timeapi.io",
    homeUrl: "https://timeapi.io/",
    cookieDomain: "timeapi.io",
    authCookieNames: [],
  },
  transcript: {
    displayName: "Transcript",
    origin: "https://github.com/yt-dlp/yt-dlp",
    homeUrl: "https://github.com/yt-dlp/yt-dlp",
    cookieDomain: "yt-dlp.github.io",
    authCookieNames: [],
  },
  translate: {
    displayName: "Translate",
    origin: "https://translate.googleapis.com",
    homeUrl: "https://translate.google.com/",
    cookieDomain: "googleapis.com",
    authCookieNames: [],
  },
  uptime: {
    displayName: "Uptime",
    origin: "https://example.com",
    homeUrl: "https://example.com/",
    cookieDomain: "example.com",
    authCookieNames: [],
  },
  uptimerobot: {
    displayName: "UptimeRobot",
    origin: "https://api.uptimerobot.com/v3",
    homeUrl: "https://dashboard.uptimerobot.com/",
    cookieDomain: "uptimerobot.com",
    authCookieNames: [],
  },
  subtitle: {
    displayName: "Subtitle Editor",
    origin: "https://ffmpeg.org",
    homeUrl: "https://ffmpeg.org/",
    cookieDomain: "ffmpeg.org",
    authCookieNames: [],
  },
  supabase: {
    displayName: "Supabase",
    origin: "https://api.supabase.com/v1",
    homeUrl: "https://supabase.com/dashboard",
    cookieDomain: "supabase.com",
    authCookieNames: [],
  },
  text: {
    displayName: "Text",
    origin: "https://en.wikipedia.org",
    homeUrl: "https://en.wikipedia.org/wiki/Text_file",
    cookieDomain: "wikipedia.org",
    authCookieNames: [],
  },
  trello: {
    displayName: "Trello",
    origin: "https://trello.com",
    homeUrl: "https://trello.com/",
    cookieDomain: "trello.com",
    authCookieNames: ["token", "dsc"],
  },
  tmdb: {
    displayName: "TMDb",
    origin: "https://www.themoviedb.org",
    homeUrl: "https://www.themoviedb.org/",
    cookieDomain: "themoviedb.org",
    authCookieNames: [],
  },
  tvmaze: {
    displayName: "TVMaze",
    origin: "https://api.tvmaze.com",
    homeUrl: "https://www.tvmaze.com/",
    cookieDomain: "tvmaze.com",
    authCookieNames: [],
  },
  vercel: {
    displayName: "Vercel",
    origin: "https://api.vercel.com",
    homeUrl: "https://vercel.com/dashboard",
    cookieDomain: "vercel.com",
    authCookieNames: [],
  },
  video: {
    displayName: "Video Editor",
    origin: "https://ffmpeg.org",
    homeUrl: "https://ffmpeg.org/",
    cookieDomain: "ffmpeg.org",
    authCookieNames: [],
  },
  weather: {
    displayName: "Weather",
    origin: "https://wttr.in",
    homeUrl: "https://wttr.in/",
    cookieDomain: "wttr.in",
    authCookieNames: [],
  },
  websearch: {
    displayName: "Web Search",
    origin: "https://html.duckduckgo.com",
    homeUrl: "https://duckduckgo.com/",
    cookieDomain: "duckduckgo.com",
    authCookieNames: [],
  },
  whatsapp: {
    displayName: "WhatsApp",
    origin: "https://web.whatsapp.com",
    homeUrl: "https://web.whatsapp.com/",
    cookieDomain: "whatsapp.com",
    authCookieNames: [],
  },
  whois: {
    displayName: "Whois",
    origin: "https://rdap.org",
    homeUrl: "https://rdap.org/",
    cookieDomain: "rdap.org",
    authCookieNames: [],
  },
  x: {
    displayName: "X",
    origin: "https://x.com",
    homeUrl: "https://x.com/",
    cookieDomain: "x.com",
    authCookieNames: ["auth_token", "ct0"],
    browserAuthCookieNames: ["auth_token"],
  },
  xml: {
    displayName: "XML",
    origin: "https://www.w3.org",
    homeUrl: "https://www.w3.org/XML/",
    cookieDomain: "w3.org",
    authCookieNames: [],
  },
  yaml: {
    displayName: "YAML",
    origin: "https://yaml.org",
    homeUrl: "https://yaml.org/",
    cookieDomain: "yaml.org",
    authCookieNames: [],
  },
  youtube: {
    displayName: "YouTube",
    origin: "https://www.youtube.com",
    homeUrl: "https://www.youtube.com/",
    cookieDomain: "youtube.com",
    authCookieNames: ["SAPISID", "LOGIN_INFO", "__Secure-3PSID", "SSID"],
  },
  "youtube-music": {
    displayName: "YouTube Music",
    origin: "https://music.youtube.com",
    homeUrl: "https://music.youtube.com/",
    cookieDomain: "youtube.com",
    authCookieNames: ["SAPISID", "LOGIN_INFO", "__Secure-3PSID", "SSID"],
  },
};

export function isPlatform(value: string): value is PlatformName {
  return (PLATFORM_NAMES as readonly string[]).includes(value);
}

export function getPlatformConfig(platform: PlatformName): PlatformConfig {
  return PLATFORM_CONFIG[platform];
}

export function getPlatformDisplayName(platform: PlatformName): string {
  return getPlatformConfig(platform).displayName;
}

export function getPlatformOrigin(platform: PlatformName): string {
  return getPlatformConfig(platform).origin;
}

export function getPlatformHomeUrl(platform: PlatformName): string {
  return getPlatformConfig(platform).homeUrl;
}

export function getPlatformCookieDomain(platform: PlatformName): string {
  return getPlatformConfig(platform).cookieDomain;
}

export function getPlatformAuthCookieNames(platform: PlatformName): readonly string[] {
  return getPlatformConfig(platform).authCookieNames;
}

export function getPlatformBrowserAuthCookieNames(platform: PlatformName): readonly string[] {
  const config = getPlatformConfig(platform);
  return config.browserAuthCookieNames ?? config.authCookieNames;
}

export function getPlatformBrowserAuthStorageKeys(platform: PlatformName): readonly string[] {
  return getPlatformConfig(platform).browserAuthStorageKeys ?? [];
}
