/* eslint-disable */
// Generated by scripts/generate-platform-registry.ts
// Do not edit by hand.

import type { PlatformDefinition } from "../core/runtime/platform-definition.js";

import { chatgptPlatformDefinition as platformDefinition0 } from "./llm/chatgpt/manifest.js";
import { claudePlatformDefinition as platformDefinition1 } from "./llm/claude/manifest.js";
import { deepSeekPlatformDefinition as platformDefinition2 } from "./llm/deepseek/manifest.js";
import { geminiPlatformDefinition as platformDefinition3 } from "./llm/gemini/manifest.js";
import { grokPlatformDefinition as platformDefinition4 } from "./llm/grok/manifest.js";
import { mistralPlatformDefinition as platformDefinition5 } from "./llm/mistral/manifest.js";
import { perplexityPlatformDefinition as platformDefinition6 } from "./llm/perplexity/manifest.js";
import { qwenPlatformDefinition as platformDefinition7 } from "./llm/qwen/manifest.js";
import { zaiPlatformDefinition as platformDefinition8 } from "./llm/zai/manifest.js";
import { archiveEditorPlatformDefinition as platformDefinition9 } from "./editor/archive/manifest.js";
import { audioEditorPlatformDefinition as platformDefinition10 } from "./editor/audio/manifest.js";
import { documentEditorPlatformDefinition as platformDefinition11 } from "./editor/document/manifest.js";
import { gifEditorPlatformDefinition as platformDefinition12 } from "./editor/gif/manifest.js";
import { imageEditorPlatformDefinition as platformDefinition13 } from "./editor/image/manifest.js";
import { pdfPlatformDefinition as platformDefinition14 } from "./editor/pdf/manifest.js";
import { subtitleEditorPlatformDefinition as platformDefinition15 } from "./editor/subtitle/manifest.js";
import { videoEditorPlatformDefinition as platformDefinition16 } from "./editor/video/manifest.js";
import { cryptoPlatformDefinition as platformDefinition17 } from "./finance/crypto/manifest.js";
import { currencyPlatformDefinition as platformDefinition18 } from "./finance/currency/manifest.js";
import { stocksPlatformDefinition as platformDefinition19 } from "./finance/stocks/manifest.js";
import { csvPlatformDefinition as platformDefinition20 } from "./data/csv/manifest.js";
import { htmlPlatformDefinition as platformDefinition21 } from "./data/html/manifest.js";
import { jsonPlatformDefinition as platformDefinition22 } from "./data/json/manifest.js";
import { markdownPlatformDefinition as platformDefinition23 } from "./data/markdown/manifest.js";
import { textPlatformDefinition as platformDefinition24 } from "./data/text/manifest.js";
import { xmlPlatformDefinition as platformDefinition25 } from "./data/xml/manifest.js";
import { yamlPlatformDefinition as platformDefinition26 } from "./data/yaml/manifest.js";
import { calendarPlatformDefinition as platformDefinition27 } from "./google/calendar/manifest.js";
import { docsPlatformDefinition as platformDefinition28 } from "./google/docs/manifest.js";
import { drivePlatformDefinition as platformDefinition29 } from "./google/drive/manifest.js";
import { formsPlatformDefinition as platformDefinition30 } from "./google/forms/manifest.js";
import { gmailPlatformDefinition as platformDefinition31 } from "./google/gmail/manifest.js";
import { sheetsPlatformDefinition as platformDefinition32 } from "./google/sheets/manifest.js";
import { geoPlatformDefinition as platformDefinition33 } from "./maps/geo/manifest.js";
import { openStreetMapPlatformDefinition as platformDefinition34 } from "./maps/openstreetmap/manifest.js";
import { osrmPlatformDefinition as platformDefinition35 } from "./maps/osrm/manifest.js";
import { aniListPlatformDefinition as platformDefinition36 } from "./movie/anilist/manifest.js";
import { imdbPlatformDefinition as platformDefinition37 } from "./movie/imdb/manifest.js";
import { justWatchPlatformDefinition as platformDefinition38 } from "./movie/justwatch/manifest.js";
import { kitsuPlatformDefinition as platformDefinition39 } from "./movie/kitsu/manifest.js";
import { letterboxdPlatformDefinition as platformDefinition40 } from "./movie/letterboxd/manifest.js";
import { myAnimeListPlatformDefinition as platformDefinition41 } from "./movie/myanimelist/manifest.js";
import { tmdbPlatformDefinition as platformDefinition42 } from "./movie/tmdb/manifest.js";
import { tvMazePlatformDefinition as platformDefinition43 } from "./movie/tvmaze/manifest.js";
import { newsPlatformDefinition as platformDefinition44 } from "./news/news/manifest.js";
import { bandcampPlatformDefinition as platformDefinition45 } from "./music/bandcamp/manifest.js";
import { deezerPlatformDefinition as platformDefinition46 } from "./music/deezer/manifest.js";
import { soundCloudPlatformDefinition as platformDefinition47 } from "./music/soundcloud/manifest.js";
import { spotifyPlatformDefinition as platformDefinition48 } from "./music/spotify/manifest.js";
import { youtubeMusicPlatformDefinition as platformDefinition49 } from "./music/youtube-music/manifest.js";
import { blueskyPlatformDefinition as platformDefinition50 } from "./social/bluesky/manifest.js";
import { facebookPlatformDefinition as platformDefinition51 } from "./social/facebook/manifest.js";
import { instagramPlatformDefinition as platformDefinition52 } from "./social/instagram/manifest.js";
import { linkedinPlatformDefinition as platformDefinition53 } from "./social/linkedin/manifest.js";
import { mastodonPlatformDefinition as platformDefinition54 } from "./social/mastodon/manifest.js";
import { pinterestPlatformDefinition as platformDefinition55 } from "./social/pinterest/manifest.js";
import { redditPlatformDefinition as platformDefinition56 } from "./social/reddit/manifest.js";
import { telegramPlatformDefinition as platformDefinition57 } from "./social/telegram/manifest.js";
import { threadsPlatformDefinition as platformDefinition58 } from "./social/threads/manifest.js";
import { tiktokPlatformDefinition as platformDefinition59 } from "./social/tiktok/manifest.js";
import { twitchPlatformDefinition as platformDefinition60 } from "./social/twitch/manifest.js";
import { whatsappPlatformDefinition as platformDefinition61 } from "./social/whatsapp/manifest.js";
import { xPlatformDefinition as platformDefinition62 } from "./social/x/manifest.js";
import { youtubePlatformDefinition as platformDefinition63 } from "./social/youtube/manifest.js";
import { amazonPlatformDefinition as platformDefinition64 } from "./shopping/amazon/manifest.js";
import { ebayPlatformDefinition as platformDefinition65 } from "./shopping/ebay/manifest.js";
import { etsyPlatformDefinition as platformDefinition66 } from "./shopping/etsy/manifest.js";
import { flipkartPlatformDefinition as platformDefinition67 } from "./shopping/flipkart/manifest.js";
import { confluencePlatformDefinition as platformDefinition68 } from "./developer/confluence/manifest.js";
import { githubPlatformDefinition as platformDefinition69 } from "./developer/github/manifest.js";
import { gitlabPlatformDefinition as platformDefinition70 } from "./developer/gitlab/manifest.js";
import { jiraPlatformDefinition as platformDefinition71 } from "./developer/jira/manifest.js";
import { linearPlatformDefinition as platformDefinition72 } from "./developer/linear/manifest.js";
import { notionPlatformDefinition as platformDefinition73 } from "./developer/notion/manifest.js";
import { trelloPlatformDefinition as platformDefinition74 } from "./developer/trello/manifest.js";
import { cloudflarePlatformDefinition as platformDefinition75 } from "./devops/cloudflare/manifest.js";
import { digitalOceanPlatformDefinition as platformDefinition76 } from "./devops/digitalocean/manifest.js";
import { flyPlatformDefinition as platformDefinition77 } from "./devops/fly/manifest.js";
import { netlifyPlatformDefinition as platformDefinition78 } from "./devops/netlify/manifest.js";
import { railwayPlatformDefinition as platformDefinition79 } from "./devops/railway/manifest.js";
import { renderPlatformDefinition as platformDefinition80 } from "./devops/render/manifest.js";
import { supabasePlatformDefinition as platformDefinition81 } from "./devops/supabase/manifest.js";
import { uptimeRobotPlatformDefinition as platformDefinition82 } from "./devops/uptimerobot/manifest.js";
import { vercelPlatformDefinition as platformDefinition83 } from "./devops/vercel/manifest.js";
import { discordBotPlatformDefinition as platformDefinition84 } from "./bot/discordbot/manifest.js";
import { githubbotPlatformDefinition as platformDefinition85 } from "./bot/githubbot/manifest.js";
import { slackbotPlatformDefinition as platformDefinition86 } from "./bot/slackbot/manifest.js";
import { telegrambotPlatformDefinition as platformDefinition87 } from "./bot/telegrambot/manifest.js";
import { cheatPlatformDefinition as platformDefinition88 } from "./tools/cheat/manifest.js";
import { dnsPlatformDefinition as platformDefinition89 } from "./tools/dns/manifest.js";
import { downloadPlatformDefinition as platformDefinition90 } from "./tools/download/manifest.js";
import { faviconPlatformDefinition as platformDefinition91 } from "./tools/favicon/manifest.js";
import { headersPlatformDefinition as platformDefinition92 } from "./tools/headers/manifest.js";
import { httpPlatformDefinition as platformDefinition93 } from "./tools/http/manifest.js";
import { ipPlatformDefinition as platformDefinition94 } from "./tools/ip/manifest.js";
import { markdownFetchPlatformDefinition as platformDefinition95 } from "./tools/markdown-fetch/manifest.js";
import { metadataPlatformDefinition as platformDefinition96 } from "./tools/metadata/manifest.js";
import { oEmbedPlatformDefinition as platformDefinition97 } from "./tools/oembed/manifest.js";
import { pageLinksPlatformDefinition as platformDefinition98 } from "./tools/page-links/manifest.js";
import { qrPlatformDefinition as platformDefinition99 } from "./tools/qr/manifest.js";
import { redirectPlatformDefinition as platformDefinition100 } from "./tools/redirect/manifest.js";
import { robotsPlatformDefinition as platformDefinition101 } from "./tools/robots/manifest.js";
import { rssPlatformDefinition as platformDefinition102 } from "./tools/rss/manifest.js";
import { screenshotPlatformDefinition as platformDefinition103 } from "./tools/screenshot/manifest.js";
import { sitemapPlatformDefinition as platformDefinition104 } from "./tools/sitemap/manifest.js";
import { sslPlatformDefinition as platformDefinition105 } from "./tools/ssl/manifest.js";
import { timePlatformDefinition as platformDefinition106 } from "./tools/time/manifest.js";
import { timezonePlatformDefinition as platformDefinition107 } from "./tools/timezone/manifest.js";
import { transcriptPlatformDefinition as platformDefinition108 } from "./tools/transcript/manifest.js";
import { translatePlatformDefinition as platformDefinition109 } from "./tools/translate/manifest.js";
import { uptimePlatformDefinition as platformDefinition110 } from "./tools/uptime/manifest.js";
import { weatherPlatformDefinition as platformDefinition111 } from "./tools/weather/manifest.js";
import { webSearchPlatformDefinition as platformDefinition112 } from "./tools/websearch/manifest.js";
import { whoisPlatformDefinition as platformDefinition113 } from "./tools/whois/manifest.js";

export function getGeneratedPlatformDefinitions(): readonly PlatformDefinition[] {
  return [
  platformDefinition0,
  platformDefinition1,
  platformDefinition2,
  platformDefinition3,
  platformDefinition4,
  platformDefinition5,
  platformDefinition6,
  platformDefinition7,
  platformDefinition8,
  platformDefinition9,
  platformDefinition10,
  platformDefinition11,
  platformDefinition12,
  platformDefinition13,
  platformDefinition14,
  platformDefinition15,
  platformDefinition16,
  platformDefinition17,
  platformDefinition18,
  platformDefinition19,
  platformDefinition20,
  platformDefinition21,
  platformDefinition22,
  platformDefinition23,
  platformDefinition24,
  platformDefinition25,
  platformDefinition26,
  platformDefinition27,
  platformDefinition28,
  platformDefinition29,
  platformDefinition30,
  platformDefinition31,
  platformDefinition32,
  platformDefinition33,
  platformDefinition34,
  platformDefinition35,
  platformDefinition36,
  platformDefinition37,
  platformDefinition38,
  platformDefinition39,
  platformDefinition40,
  platformDefinition41,
  platformDefinition42,
  platformDefinition43,
  platformDefinition44,
  platformDefinition45,
  platformDefinition46,
  platformDefinition47,
  platformDefinition48,
  platformDefinition49,
  platformDefinition50,
  platformDefinition51,
  platformDefinition52,
  platformDefinition53,
  platformDefinition54,
  platformDefinition55,
  platformDefinition56,
  platformDefinition57,
  platformDefinition58,
  platformDefinition59,
  platformDefinition60,
  platformDefinition61,
  platformDefinition62,
  platformDefinition63,
  platformDefinition64,
  platformDefinition65,
  platformDefinition66,
  platformDefinition67,
  platformDefinition68,
  platformDefinition69,
  platformDefinition70,
  platformDefinition71,
  platformDefinition72,
  platformDefinition73,
  platformDefinition74,
  platformDefinition75,
  platformDefinition76,
  platformDefinition77,
  platformDefinition78,
  platformDefinition79,
  platformDefinition80,
  platformDefinition81,
  platformDefinition82,
  platformDefinition83,
  platformDefinition84,
  platformDefinition85,
  platformDefinition86,
  platformDefinition87,
  platformDefinition88,
  platformDefinition89,
  platformDefinition90,
  platformDefinition91,
  platformDefinition92,
  platformDefinition93,
  platformDefinition94,
  platformDefinition95,
  platformDefinition96,
  platformDefinition97,
  platformDefinition98,
  platformDefinition99,
  platformDefinition100,
  platformDefinition101,
  platformDefinition102,
  platformDefinition103,
  platformDefinition104,
  platformDefinition105,
  platformDefinition106,
  platformDefinition107,
  platformDefinition108,
  platformDefinition109,
  platformDefinition110,
  platformDefinition111,
  platformDefinition112,
  platformDefinition113,
  ];
}
