import { spawn } from "node:child_process";

import { MikaCliError, isMikaCliError } from "../../../errors.js";
import { parseSrt, parseVtt, serializeSubtitleDocument } from "../../editor/subtitle/adapter.js";
import { normalizePublicHttpUrl } from "../shared/url.js";

import type { AdapterActionResult, Platform } from "../../../types.js";
import type { SubtitleCue } from "../../editor/subtitle/adapter.js";

type TranscriptInput = {
  target: string;
  lang?: string;
  auto?: boolean;
  format?: string;
  timeoutMs?: number;
};

type TranscriptFormat = "txt" | "vtt" | "srt" | "json";
type TranscriptSourceFormat = "vtt" | "srt" | "json3";

type YtDlpSubtitleTrack = {
  ext?: string;
  url?: string;
  name?: string;
  protocol?: string;
};

type YtDlpTranscriptInfo = {
  id?: string;
  title?: string;
  uploader?: string;
  duration?: number;
  extractor?: string;
  webpage_url?: string;
  original_url?: string;
  subtitles?: Record<string, YtDlpSubtitleTrack[]>;
  automatic_captions?: Record<string, YtDlpSubtitleTrack[]>;
};

type SelectedTranscriptTrack = {
  languageCode: string;
  language: string | null;
  autoGenerated: boolean;
  track: YtDlpSubtitleTrack & {
    ext: TranscriptSourceFormat;
    url: string;
  };
};

type TranscriptPayload = {
  transcript: string;
  content?: string;
  cues: SubtitleCue[];
};

export class TranscriptAdapter {
  readonly platform: Platform = "transcript" as Platform;
  readonly displayName = "Transcript";

  async fetch(input: TranscriptInput): Promise<AdapterActionResult> {
    const target = normalizePublicHttpUrl(input.target);
    const timeoutMs = clampNumber(input.timeoutMs ?? 15000, 1000, 60000);
    const format = normalizeTranscriptFormat(input.format);

    await this.requireCommand("yt-dlp", ["--version"], "YTDLP_NOT_FOUND", "yt-dlp is required for tools transcript.");

    let info: YtDlpTranscriptInfo;
    try {
      const { stdout } = await this.runProcess("yt-dlp", [
        "--no-warnings",
        "--dump-single-json",
        "--skip-download",
        target,
      ]);
      info = parseYtDlpTranscriptInfo(stdout);
    } catch (error) {
      if (isMikaCliError(error)) {
        throw error;
      }

      throw new MikaCliError("TRANSCRIPT_INFO_FAILED", "Failed to inspect transcript metadata with yt-dlp.", {
        cause: error,
        details: { target },
      });
    }

    const selected = selectTranscriptTrack(info, {
      lang: input.lang,
      preferAuto: Boolean(input.auto),
      outputFormat: format,
    });
    const rawContent = await fetchTranscriptTrack(selected.track.url, timeoutMs, target);
    const payload = buildTranscriptPayload(rawContent, selected.track.ext, format);
    const finalUrl = info.webpage_url ?? info.original_url ?? target;

    return {
      ok: true,
      platform: this.platform,
      account: "public",
      action: "transcript",
      message: `Loaded ${selected.autoGenerated ? "auto-generated " : ""}transcript${info.title ? ` for ${info.title}` : ""}.`,
      id: info.id,
      url: finalUrl,
      data: {
        target,
        finalUrl,
        title: info.title ?? null,
        uploader: info.uploader ?? null,
        extractor: info.extractor ?? null,
        durationSeconds: info.duration ?? null,
        durationLabel: typeof info.duration === "number" ? formatDuration(info.duration) : null,
        languageCode: selected.languageCode,
        language: selected.language ?? selected.languageCode,
        autoGenerated: selected.autoGenerated,
        format,
        sourceFormat: selected.track.ext,
        trackUrl: selected.track.url,
        trackProtocol: selected.track.protocol ?? null,
        cueCount: payload.cues.length,
        transcript: payload.transcript,
        content: payload.content,
        cues: payload.cues.map((cue) => ({
          startMs: cue.startMs,
          endMs: cue.endMs,
          text: cue.text.join("\n"),
          lines: cue.text,
        })),
        availableLanguages: {
          subtitles: Object.keys(info.subtitles ?? {}),
          automatic: Object.keys(info.automatic_captions ?? {}),
        },
        meta: {
          count: payload.cues.length,
          listKey: "cues",
        },
      },
    };
  }

  private async requireCommand(
    command: string,
    args: string[],
    errorCode: string,
    errorMessage: string,
  ): Promise<void> {
    try {
      await this.runProcess(command, args);
    } catch (error) {
      if (
        error instanceof Error &&
        "cause" in error &&
        error.cause &&
        typeof error.cause === "object" &&
        "code" in error.cause &&
        error.cause.code === "ENOENT"
      ) {
        throw new MikaCliError(errorCode, errorMessage, {
          details: { command },
          cause: error,
        });
      }

      throw error;
    }
  }

  private async runProcess(command: string, args: string[]): Promise<{ stdout: string; stderr: string }> {
    return new Promise((resolvePromise, rejectPromise) => {
      const child = spawn(command, args, {
        stdio: ["ignore", "pipe", "pipe"],
      });

      let stdout = "";
      let stderr = "";

      child.stdout.on("data", (chunk) => {
        stdout += String(chunk);
      });

      child.stderr.on("data", (chunk) => {
        stderr += String(chunk);
      });

      child.on("error", (error) => {
        rejectPromise(new Error(`Failed to start ${command}.`, { cause: error }));
      });

      child.on("close", (code) => {
        if (code === 0) {
          resolvePromise({ stdout, stderr });
          return;
        }

        rejectPromise(
          new MikaCliError("PROCESS_FAILED", `${command} exited with code ${code ?? "unknown"}.`, {
            details: {
              command,
              args,
              code: code ?? undefined,
              stderr: stderr || undefined,
            },
          }),
        );
      });
    });
  }
}

export const transcriptAdapter = new TranscriptAdapter();

export function normalizeTranscriptFormat(value?: string): TranscriptFormat {
  const normalized = value?.trim().toLowerCase() ?? "txt";
  if (normalized === "txt" || normalized === "vtt" || normalized === "srt" || normalized === "json") {
    return normalized;
  }

  throw new MikaCliError(
    "TRANSCRIPT_FORMAT_INVALID",
    `Invalid transcript format "${value}". Use txt, vtt, srt, or json.`,
  );
}

export function selectTranscriptTrack(
  info: YtDlpTranscriptInfo,
  input: {
    lang?: string;
    preferAuto?: boolean;
    outputFormat: TranscriptFormat;
  },
): SelectedTranscriptTrack {
  const subtitles = info.subtitles ?? {};
  const automaticCaptions = info.automatic_captions ?? {};
  const requestedLanguage = normalizeLanguageCode(input.lang);
  const sourceOrder = input.preferAuto
    ? [
        { tracksByLanguage: automaticCaptions, autoGenerated: true },
        { tracksByLanguage: subtitles, autoGenerated: false },
      ]
    : [
        { tracksByLanguage: subtitles, autoGenerated: false },
        { tracksByLanguage: automaticCaptions, autoGenerated: true },
      ];

  for (const source of sourceOrder) {
    const availableLanguageCodes = Object.keys(source.tracksByLanguage);
    const languageCode = pickLanguageCode(availableLanguageCodes, requestedLanguage);
    if (!languageCode) {
      continue;
    }

    const track = pickBestTranscriptTrack(source.tracksByLanguage[languageCode] ?? [], input.outputFormat);
    if (!track) {
      continue;
    }

    return {
      languageCode,
      language: typeof track.name === "string" && track.name.trim().length > 0 ? track.name.trim() : null,
      autoGenerated: source.autoGenerated,
      track,
    };
  }

  const availableLanguages = {
    subtitles: Object.keys(subtitles),
    automatic: Object.keys(automaticCaptions),
  };

  if (requestedLanguage) {
    throw new MikaCliError("TRANSCRIPT_LANGUAGE_UNAVAILABLE", `No subtitles found for language "${requestedLanguage}".`, {
      details: {
        requestedLanguage,
        availableLanguages,
      },
    });
  }

  throw new MikaCliError("TRANSCRIPT_UNAVAILABLE", "No subtitles or captions were found for this URL.", {
    details: {
      availableLanguages,
    },
  });
}

export function buildTranscriptPayload(
  rawContent: string,
  sourceFormat: TranscriptSourceFormat,
  outputFormat: TranscriptFormat,
): TranscriptPayload {
  const cues = parseTranscriptSource(rawContent, sourceFormat);
  if (cues.length === 0) {
    throw new MikaCliError("TRANSCRIPT_EMPTY", "The selected transcript track did not contain any cues.");
  }

  const transcript = renderTranscriptText(cues);

  if (outputFormat === "json") {
    return { transcript, cues };
  }

  if (outputFormat === "txt") {
    return { transcript, cues, content: transcript };
  }

  if (outputFormat === "vtt") {
    return {
      transcript,
      cues,
      content: sourceFormat === "vtt" ? ensureTrailingNewline(rawContent) : serializeSubtitleDocument(cues, "vtt"),
    };
  }

  return {
    transcript,
    cues,
    content: sourceFormat === "srt" ? ensureTrailingNewline(rawContent) : serializeSubtitleDocument(cues, "srt"),
  };
}

export function renderTranscriptText(cues: readonly SubtitleCue[]): string {
  const lines: string[] = [];
  let previous = "";

  for (const cue of cues) {
    const text = cue.text
      .map((line) => line.replace(/\s+/gu, " ").trim())
      .filter((line) => line.length > 0)
      .join(" ")
      .trim();

    if (!text || text === previous) {
      continue;
    }

    lines.push(text);
    previous = text;
  }

  return lines.join("\n");
}

export function parseJson3Transcript(content: string): SubtitleCue[] {
  let parsed: unknown;
  try {
    parsed = JSON.parse(content) as { events?: unknown };
  } catch (error) {
    throw new MikaCliError("TRANSCRIPT_JSON3_PARSE_FAILED", "Failed to parse json3 transcript data.", {
      cause: error,
    });
  }

  const events =
    parsed && typeof parsed === "object" && "events" in parsed && Array.isArray(parsed.events) ? parsed.events : [];
  const cues: SubtitleCue[] = [];

  for (const event of events) {
    const startMs = getFiniteNumber(event, "tStartMs");
    const durationMs = getFiniteNumber(event, "dDurationMs");
    const segs =
      event && typeof event === "object" && "segs" in event && Array.isArray(event.segs) ? event.segs : [];

    if (!Number.isFinite(startMs) || !Number.isFinite(durationMs) || durationMs <= 0 || segs.length === 0) {
      continue;
    }

    const text = segs
      .map((segment: unknown) =>
        segment && typeof segment === "object" && "utf8" in segment && typeof segment.utf8 === "string"
          ? segment.utf8
          : "",
      )
      .join("")
      .replace(/\u200b/gu, "")
      .replace(/\r\n/gu, "\n")
      .trim();

    if (!text) {
      continue;
    }

    const lines = text
      .split("\n")
      .map((line: string) => line.trim())
      .filter((line: string) => line.length > 0);
    if (lines.length === 0) {
      continue;
    }

    cues.push({
      startMs: Math.max(0, Math.round(startMs)),
      endMs: Math.max(Math.round(startMs) + 1, Math.round(startMs + durationMs)),
      text: lines,
    });
  }

  return cues;
}

function parseTranscriptSource(content: string, sourceFormat: TranscriptSourceFormat): SubtitleCue[] {
  if (sourceFormat === "srt") {
    return parseSrt(content);
  }
  if (sourceFormat === "json3") {
    return parseJson3Transcript(content);
  }
  return parseVtt(content);
}

function normalizeLanguageCode(value?: string): string | undefined {
  const normalized = value?.trim().toLowerCase();
  return normalized ? normalized : undefined;
}

function pickLanguageCode(availableLanguageCodes: string[], requestedLanguage?: string): string | undefined {
  if (availableLanguageCodes.length === 0) {
    return undefined;
  }

  if (requestedLanguage) {
    const matches = availableLanguageCodes
      .map((languageCode, index) => ({
        languageCode,
        index,
        score: scoreLanguageMatch(languageCode, requestedLanguage),
      }))
      .filter((entry) => entry.score > 0)
      .sort((left, right) => right.score - left.score || left.index - right.index);

    return matches[0]?.languageCode;
  }

  return availableLanguageCodes
    .map((languageCode, index) => ({
      languageCode,
      index,
      score:
        normalizeLanguageCode(languageCode) === "en"
          ? 200
          : normalizeLanguageCode(languageCode)?.startsWith("en-")
            ? 180
            : 0,
    }))
    .sort((left, right) => right.score - left.score || left.index - right.index)[0]?.languageCode;
}

function scoreLanguageMatch(languageCode: string, requestedLanguage: string): number {
  const candidate = normalizeLanguageCode(languageCode);
  if (!candidate) {
    return 0;
  }

  if (candidate === requestedLanguage) {
    return 100;
  }

  const candidateBase = candidate.split(/[-_]/u)[0];
  const requestedBase = requestedLanguage.split(/[-_]/u)[0];

  if (candidateBase === requestedBase) {
    return 80;
  }

  if (candidate.startsWith(`${requestedLanguage}-`) || candidate.startsWith(`${requestedLanguage}_`)) {
    return 70;
  }

  if (requestedLanguage.startsWith(`${candidate}-`) || requestedLanguage.startsWith(`${candidate}_`)) {
    return 60;
  }

  return 0;
}

function pickBestTranscriptTrack(
  tracks: readonly YtDlpSubtitleTrack[],
  outputFormat: TranscriptFormat,
): SelectedTranscriptTrack["track"] | undefined {
  const candidates = tracks
    .map((track, index) => ({
      track,
      index,
      ext: normalizeTrackExt(track.ext),
    }))
    .filter((entry): entry is { track: YtDlpSubtitleTrack; index: number; ext: TranscriptSourceFormat } =>
      Boolean(entry.ext && typeof entry.track.url === "string" && entry.track.url.trim().length > 0),
    )
    .sort((left, right) => {
      const scoreDelta = scoreTranscriptTrack(right.track, right.ext, outputFormat) - scoreTranscriptTrack(left.track, left.ext, outputFormat);
      return scoreDelta || left.index - right.index;
    });

  const selected = candidates[0];
  if (!selected) {
    return undefined;
  }

  return {
    ...selected.track,
    ext: selected.ext,
    url: selected.track.url!.trim(),
  };
}

function normalizeTrackExt(value?: string): TranscriptSourceFormat | undefined {
  const normalized = value?.trim().toLowerCase();
  if (normalized === "vtt" || normalized === "srt" || normalized === "json3") {
    return normalized;
  }
  return undefined;
}

function scoreTranscriptTrack(
  track: YtDlpSubtitleTrack,
  ext: TranscriptSourceFormat,
  outputFormat: TranscriptFormat,
): number {
  const protocol = track.protocol?.toLowerCase() ?? "";
  const url = track.url?.toLowerCase() ?? "";

  let score = 0;
  if (outputFormat === "srt") {
    score += ext === "srt" ? 120 : ext === "vtt" ? 100 : 80;
  } else if (outputFormat === "vtt") {
    score += ext === "vtt" ? 120 : ext === "srt" ? 100 : 80;
  } else {
    score += ext === "vtt" ? 120 : ext === "srt" ? 100 : 90;
  }

  if (protocol.includes("m3u8")) {
    score -= 60;
  }
  if (protocol.includes("dash")) {
    score -= 40;
  }
  if (url.includes("/manifest/")) {
    score -= 25;
  }

  return score;
}

async function fetchTranscriptTrack(trackUrl: string, timeoutMs: number, target: string): Promise<string> {
  let response: Response;
  try {
    response = await fetch(trackUrl, {
      redirect: "follow",
      signal: AbortSignal.timeout(timeoutMs),
      headers: {
        accept: "text/plain,text/vtt,application/json,*/*",
        "accept-language": "en-US,en;q=0.9",
        "cache-control": "no-cache",
        pragma: "no-cache",
        "user-agent": "Mozilla/5.0 (compatible; MikaCLI/1.0; +https://github.com/)",
      },
    });
  } catch (error) {
    throw new MikaCliError("TRANSCRIPT_FETCH_FAILED", "Unable to fetch the selected transcript track.", {
      cause: error,
      details: {
        target,
        trackUrl,
      },
    });
  }

  if (!response.ok) {
    throw new MikaCliError("TRANSCRIPT_FETCH_FAILED", `Transcript request failed with ${response.status} ${response.statusText}.`, {
      details: {
        target,
        trackUrl,
        status: response.status,
        statusText: response.statusText,
      },
    });
  }

  return await response.text();
}

function parseYtDlpTranscriptInfo(stdout: string): YtDlpTranscriptInfo {
  try {
    return JSON.parse(stdout) as YtDlpTranscriptInfo;
  } catch (error) {
    throw new MikaCliError("TRANSCRIPT_INFO_PARSE_FAILED", "yt-dlp did not return valid transcript metadata.", {
      cause: error,
    });
  }
}

function getFiniteNumber(value: unknown, key: string): number {
  if (!value || typeof value !== "object" || !(key in value)) {
    return Number.NaN;
  }

  const candidate = value[key as keyof typeof value];
  return typeof candidate === "number" && Number.isFinite(candidate) ? candidate : Number.NaN;
}

function ensureTrailingNewline(value: string): string {
  return value.endsWith("\n") ? value : `${value}\n`;
}

function formatDuration(seconds: number): string {
  const totalSeconds = Math.max(0, Math.round(seconds));
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const remainingSeconds = totalSeconds % 60;

  if (hours > 0) {
    return `${hours}:${String(minutes).padStart(2, "0")}:${String(remainingSeconds).padStart(2, "0")}`;
  }

  return `${minutes}:${String(remainingSeconds).padStart(2, "0")}`;
}

function clampNumber(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value));
}
