import { printActionResult } from "../../../utils/cli.js";
import { printJson } from "../../../utils/output.js";

import type { AdapterActionResult } from "../../../types.js";

export function printTranscriptResult(result: AdapterActionResult, json: boolean): void {
  if (json) {
    printJson(result);
    return;
  }

  printActionResult(result, false);

  const data = result.data ?? {};

  if (typeof data.title === "string" && data.title) {
    console.log(`title: ${data.title}`);
  }

  if (typeof data.uploader === "string" && data.uploader) {
    console.log(`uploader: ${data.uploader}`);
  }

  if (typeof data.durationLabel === "string" && data.durationLabel) {
    console.log(`duration: ${data.durationLabel}`);
  }

  if (typeof data.language === "string" && data.language) {
    console.log(`language: ${data.language}`);
  }

  if (typeof data.autoGenerated === "boolean") {
    console.log(`auto-generated: ${data.autoGenerated ? "yes" : "no"}`);
  }

  if (typeof data.format === "string" && data.format) {
    console.log(`format: ${data.format}`);
  }

  if (typeof data.sourceFormat === "string" && data.sourceFormat) {
    console.log(`source-format: ${data.sourceFormat}`);
  }

  if (typeof data.cueCount === "number") {
    console.log(`cues: ${data.cueCount}`);
  }

  const content = typeof data.content === "string" ? data.content : undefined;
  const cues = Array.isArray(data.cues) ? data.cues : undefined;
  const transcript = typeof data.transcript === "string" ? data.transcript : undefined;

  if (content && content.length > 0) {
    console.log("");
    process.stdout.write(content.endsWith("\n") ? content : `${content}\n`);
    return;
  }

  if (cues) {
    console.log("");
    console.log(JSON.stringify(cues, null, 2));
    return;
  }

  if (transcript && transcript.length > 0) {
    console.log("");
    process.stdout.write(transcript.endsWith("\n") ? transcript : `${transcript}\n`);
  }
}
