import { describe, expect, test } from "bun:test";

import {
  buildTranscriptPayload,
  normalizeTranscriptFormat,
  parseJson3Transcript,
  renderTranscriptText,
  selectTranscriptTrack,
} from "../adapter.js";

describe("transcript adapter helpers", () => {
  test("normalizes transcript output formats", () => {
    expect(normalizeTranscriptFormat()).toBe("txt");
    expect(normalizeTranscriptFormat("SRT")).toBe("srt");
    expect(normalizeTranscriptFormat("json")).toBe("json");
  });

  test("prefers manual subtitles by default", () => {
    const selection = selectTranscriptTrack({
      subtitles: {
        en: [
          { ext: "vtt", url: "https://example.com/manual.vtt", name: "English" },
        ],
      },
      automatic_captions: {
        en: [
          { ext: "vtt", url: "https://example.com/auto.vtt", name: "English (auto)" },
        ],
      },
    }, {
      outputFormat: "txt",
    });

    expect(selection.autoGenerated).toBe(false);
    expect(selection.track.url).toBe("https://example.com/manual.vtt");
  });

  test("can prefer auto captions when requested", () => {
    const selection = selectTranscriptTrack({
      subtitles: {
        en: [
          { ext: "vtt", url: "https://example.com/manual.vtt", name: "English" },
        ],
      },
      automatic_captions: {
        en: [
          { ext: "vtt", url: "https://example.com/auto.vtt", name: "English (auto)" },
        ],
      },
    }, {
      outputFormat: "txt",
      preferAuto: true,
    });

    expect(selection.autoGenerated).toBe(true);
    expect(selection.track.url).toBe("https://example.com/auto.vtt");
  });

  test("matches regional subtitle variants for a requested language", () => {
    const selection = selectTranscriptTrack({
      subtitles: {
        "en-US": [
          { ext: "vtt", url: "https://example.com/en-us.vtt", name: "English (US)" },
        ],
        hi: [
          { ext: "vtt", url: "https://example.com/hi.vtt", name: "Hindi" },
        ],
      },
    }, {
      lang: "en",
      outputFormat: "txt",
    });

    expect(selection.languageCode).toBe("en-US");
  });

  test("avoids manifest-backed caption tracks when direct vtt or srt is available", () => {
    const selection = selectTranscriptTrack({
      subtitles: {
        en: [
          { ext: "vtt", url: "https://example.com/manifest.m3u8", protocol: "m3u8_native", name: "English" },
          { ext: "srt", url: "https://example.com/direct.srt", name: "English" },
        ],
      },
    }, {
      outputFormat: "txt",
    });

    expect(selection.track.url).toBe("https://example.com/direct.srt");
  });

  test("renders transcript text with consecutive duplicates removed", () => {
    expect(renderTranscriptText([
      { startMs: 0, endMs: 1000, text: ["Hello world"] },
      { startMs: 1000, endMs: 2000, text: ["Hello world"] },
      { startMs: 2000, endMs: 3000, text: ["How are you?"] },
    ])).toBe("Hello world\nHow are you?");
  });

  test("parses json3 transcript events into cues", () => {
    expect(parseJson3Transcript(JSON.stringify({
      events: [
        { tStartMs: 1200, dDurationMs: 800, segs: [{ utf8: "Hello" }, { utf8: "\nworld" }] },
        { tStartMs: 2200, dDurationMs: 500, segs: [{ utf8: "Again" }] },
      ],
    }))).toEqual([
      { startMs: 1200, endMs: 2000, text: ["Hello", "world"] },
      { startMs: 2200, endMs: 2700, text: ["Again"] },
    ]);
  });

  test("builds txt output from vtt content", () => {
    const payload = buildTranscriptPayload([
      "WEBVTT",
      "",
      "00:00:01.000 --> 00:00:02.000",
      "Hello world",
      "",
      "00:00:03.000 --> 00:00:04.000",
      "Second line",
      "",
    ].join("\n"), "vtt", "txt");

    expect(payload.transcript).toBe("Hello world\nSecond line");
    expect(payload.content).toBe("Hello world\nSecond line");
  });

  test("converts vtt input into srt output", () => {
    const payload = buildTranscriptPayload([
      "WEBVTT",
      "",
      "00:00:01.000 --> 00:00:02.000",
      "Hello world",
      "",
    ].join("\n"), "vtt", "srt");

    expect(payload.content).toContain("00:00:01,000 --> 00:00:02,000");
    expect(payload.content).toContain("Hello world");
  });
});
