import { readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import type { PlatformCategory, PlatformDefinition } from "../src/core/runtime/platform-definition.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = dirname(__dirname);
const platformRoot = join(repoRoot, "src", "platforms");
const registryOutputPath = join(platformRoot, "generated-registry.ts");
const metadataOutputPath = join(platformRoot, "generated-metadata.ts");
const CATEGORY_ORDER: readonly PlatformCategory[] = [
  "llm",
  "editor",
  "finance",
  "data",
  "google",
  "maps",
  "movie",
  "news",
  "music",
  "social",
  "shopping",
  "developer",
  "devops",
  "bot",
  "tools",
  "forum",
] as const;

type DiscoveredPlatformManifest = {
  readonly sourcePath: string;
  readonly importPath: string;
  readonly exportName: string;
  readonly definition: PlatformDefinition;
};

export async function generatePlatformRegistry(): Promise<void> {
  const manifests = await discoverPlatformManifests();
  await writeFile(registryOutputPath, renderPlatformRegistry(manifests), "utf8");
  await writeFile(metadataOutputPath, renderPlatformMetadata(manifests), "utf8");
}

export async function discoverPlatformManifests(): Promise<DiscoveredPlatformManifest[]> {
  const manifestPaths = await collectManifestPaths(platformRoot);
  const manifests: DiscoveredPlatformManifest[] = [];
  const seenIds = new Map<string, string>();

  for (const sourcePath of manifestPaths) {
    const module = await import(pathToFileURL(sourcePath).href);
    const platformExports = Object.entries(module).filter((entry): entry is [string, PlatformDefinition] => isPlatformDefinition(entry[1]));

    if (platformExports.length !== 1) {
      throw new Error(
        `Expected exactly one PlatformDefinition export in ${relative(repoRoot, sourcePath)}, found ${platformExports.length}.`,
      );
    }

    const [exportName, definition] = platformExports[0];
    const existingPath = seenIds.get(definition.id);
    if (existingPath) {
      throw new Error(
        `Duplicate platform id "${definition.id}" found in ${relative(repoRoot, existingPath)} and ${relative(repoRoot, sourcePath)}.`,
      );
    }
    seenIds.set(definition.id, sourcePath);

    manifests.push({
      sourcePath,
      importPath: toGeneratedImportPath(sourcePath),
      exportName,
      definition,
    });
  }

  return manifests.sort(compareDiscoveredPlatforms);
}

async function collectManifestPaths(root: string): Promise<string[]> {
  const entries = await readdir(root, { withFileTypes: true });
  const results: string[] = [];

  for (const entry of entries) {
    const entryPath = join(root, entry.name);

    if (entry.isDirectory()) {
      if (entry.name === "shared" || entry.name === "__tests__") {
        continue;
      }
      results.push(...(await collectManifestPaths(entryPath)));
      continue;
    }

    if (entry.isFile() && entry.name === "manifest.ts") {
      results.push(entryPath);
    }
  }

  return results.sort((left, right) => left.localeCompare(right));
}

function compareDiscoveredPlatforms(left: DiscoveredPlatformManifest, right: DiscoveredPlatformManifest): number {
  const categoryDelta = compareCategory(left.definition.category, right.definition.category);
  if (categoryDelta !== 0) {
    return categoryDelta;
  }

  const idDelta = left.definition.id.localeCompare(right.definition.id);
  if (idDelta !== 0) {
    return idDelta;
  }

  return left.sourcePath.localeCompare(right.sourcePath);
}

function compareCategory(left: PlatformCategory, right: PlatformCategory): number {
  const leftIndex = CATEGORY_ORDER.indexOf(left);
  const rightIndex = CATEGORY_ORDER.indexOf(right);
  const normalizedLeft = leftIndex === -1 ? Number.MAX_SAFE_INTEGER : leftIndex;
  const normalizedRight = rightIndex === -1 ? Number.MAX_SAFE_INTEGER : rightIndex;
  return normalizedLeft - normalizedRight;
}

function toGeneratedImportPath(sourcePath: string): string {
  const relativePath = relative(platformRoot, sourcePath).split(sep).join("/");
  return `./${relativePath.replace(/\.ts$/, ".js")}`;
}

function renderPlatformRegistry(manifests: readonly DiscoveredPlatformManifest[]): string {
  const importLines = manifests.map((manifest, index) =>
    `import { ${manifest.exportName} as platformDefinition${index} } from "${manifest.importPath}";`,
  );
  const definitionLines = manifests.map((_, index) => `  platformDefinition${index},`);

  return `/* eslint-disable */
// Generated by scripts/generate-platform-registry.ts
// Do not edit by hand.

import type { PlatformDefinition } from "../core/runtime/platform-definition.js";

${importLines.join("\n")}

export function getGeneratedPlatformDefinitions(): readonly PlatformDefinition[] {
  return [
${definitionLines.join("\n")}
  ];
}
`;
}

function renderPlatformMetadata(manifests: readonly DiscoveredPlatformManifest[]): string {
  const names = manifests.map((manifest) => `  "${manifest.definition.id}",`);
  const displayNames = manifests.map((manifest) => `  "${manifest.definition.id}": "${escapeStringLiteral(manifest.definition.displayName)}",`);

  return `/* eslint-disable */
// Generated by scripts/generate-platform-registry.ts
// Do not edit by hand.

export const GENERATED_PLATFORM_NAMES = [
${names.join("\n")}
] as const;

export type GeneratedPlatformName = (typeof GENERATED_PLATFORM_NAMES)[number];

export const GENERATED_PLATFORM_DISPLAY_NAMES: Record<GeneratedPlatformName, string> = {
${displayNames.join("\n")}
};
`;
}

function isPlatformDefinition(value: unknown): value is PlatformDefinition {
  if (!value || typeof value !== "object") {
    return false;
  }

  const candidate = value as Partial<PlatformDefinition>;
  return (
    typeof candidate.id === "string"
    && typeof candidate.category === "string"
    && typeof candidate.displayName === "string"
    && typeof candidate.description === "string"
    && Array.isArray(candidate.authStrategies)
  );
}

function escapeStringLiteral(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

if (import.meta.main) {
  await generatePlatformRegistry();
}
